/* eslint-disable */
// GENERATED by tools/build-engine.py from forauls-tiger-tee.html — do not edit by hand.
// WebGPU cloth-simulated tee: XPBD cloth on the GPU, studio lighting, prints as textures.

/**
 * Mounts the 3D tee on `canvas`.
 * options: { front, back: { src, rect? }, colour, mode, yaw, autoSpin, framing: { dy, dist }, lite,
 *            onYaw(rad), onMode(mode), onToast(msg), onInteract(), onError(err) }
 * `lite` starts (and stays) on the cheaper end of the quality ladder — used when
 * rebuilding after the GPU was reset.
 * Resolves to an API object; rejects if WebGPU is unavailable or the GPU is lost
 * during start-up. onError fires if the device is lost afterwards (driver reset,
 * TDR, sleep/wake); the instance is dead then and should be destroyed and rebuilt.
 */
export async function createTeeViewer(canvas, options = {}) {
const opts = options;
const cleanups = [];
const listen = (t, type, fn, o) => { t.addEventListener(type, fn, o); cleanups.push(() => t.removeEventListener(type, fn, o)); };
function toast(msg) { opts.onToast?.(msg); }
function updateFlipLabel() {}

/* =====================================================================
   Small vector / matrix helpers (column-major, WebGPU clip z in [0,1])
   ===================================================================== */
const v3 = {
  add: (a, b) => [a[0] + b[0], a[1] + b[1], a[2] + b[2]],
  sub: (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]],
  scale: (a, s) => [a[0] * s, a[1] * s, a[2] * s],
  dot: (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2],
  cross: (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]],
  len: (a) => Math.hypot(a[0], a[1], a[2]),
  norm: (a) => { const l = Math.hypot(a[0], a[1], a[2]) || 1; return [a[0] / l, a[1] / l, a[2] / l]; },
  lerp: (a, b, t) => [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t],
};

const m4 = {
  perspective(fovy, aspect, near, far) {
    const f = 1 / Math.tan(fovy / 2), nf = 1 / (near - far);
    return new Float32Array([f / aspect, 0, 0, 0, 0, f, 0, 0, 0, 0, far * nf, -1, 0, 0, far * near * nf, 0]);
  },
  ortho(l, r, b, t, n, f) {
    return new Float32Array([2 / (r - l), 0, 0, 0, 0, 2 / (t - b), 0, 0, 0, 0, 1 / (n - f), 0,
      (l + r) / (l - r), (t + b) / (b - t), n / (n - f), 1]);
  },
  lookAt(eye, target, up) {
    const z = v3.norm(v3.sub(eye, target)), x = v3.norm(v3.cross(up, z)), y = v3.cross(z, x);
    return new Float32Array([x[0], y[0], z[0], 0, x[1], y[1], z[1], 0, x[2], y[2], z[2], 0,
      -v3.dot(x, eye), -v3.dot(y, eye), -v3.dot(z, eye), 1]);
  },
  mul(a, b) {
    const o = new Float32Array(16);
    for (let c = 0; c < 4; c++) for (let r = 0; r < 4; r++) {
      let s = 0; for (let k = 0; k < 4; k++) s += a[k * 4 + r] * b[c * 4 + k]; o[c * 4 + r] = s;
    }
    return o;
  },
  invert(m) {
    const a = m, o = new Float32Array(16);
    const b00 = a[0] * a[5] - a[1] * a[4], b01 = a[0] * a[6] - a[2] * a[4], b02 = a[0] * a[7] - a[3] * a[4];
    const b03 = a[1] * a[6] - a[2] * a[5], b04 = a[1] * a[7] - a[3] * a[5], b05 = a[2] * a[7] - a[3] * a[6];
    const b06 = a[8] * a[13] - a[9] * a[12], b07 = a[8] * a[14] - a[10] * a[12], b08 = a[8] * a[15] - a[11] * a[12];
    const b09 = a[9] * a[14] - a[10] * a[13], b10 = a[9] * a[15] - a[11] * a[13], b11 = a[10] * a[15] - a[11] * a[14];
    const d = 1 / (b00 * b11 - b01 * b10 + b02 * b09 + b03 * b08 - b04 * b07 + b05 * b06);
    o[0] = (a[5] * b11 - a[6] * b10 + a[7] * b09) * d; o[1] = (a[2] * b10 - a[1] * b11 - a[3] * b09) * d;
    o[2] = (a[13] * b05 - a[14] * b04 + a[15] * b03) * d; o[3] = (a[10] * b04 - a[9] * b05 - a[11] * b03) * d;
    o[4] = (a[6] * b08 - a[4] * b11 - a[7] * b07) * d; o[5] = (a[0] * b11 - a[2] * b08 + a[3] * b07) * d;
    o[6] = (a[14] * b02 - a[12] * b05 - a[15] * b01) * d; o[7] = (a[8] * b05 - a[10] * b02 + a[11] * b01) * d;
    o[8] = (a[4] * b10 - a[5] * b08 + a[7] * b06) * d; o[9] = (a[1] * b08 - a[0] * b10 - a[3] * b06) * d;
    o[10] = (a[12] * b04 - a[13] * b02 + a[15] * b00) * d; o[11] = (a[9] * b02 - a[8] * b04 - a[11] * b00) * d;
    o[12] = (a[5] * b07 - a[4] * b09 - a[6] * b06) * d; o[13] = (a[0] * b09 - a[1] * b07 + a[2] * b06) * d;
    o[14] = (a[13] * b01 - a[12] * b03 - a[14] * b00) * d; o[15] = (a[8] * b03 - a[9] * b01 + a[10] * b00) * d;
    return o;
  },
};

const clamp = (x, a, b) => Math.min(b, Math.max(a, x));
const smoothstep = (a, b, x) => { const t = clamp((x - a) / (b - a), 0, 1); return t * t * (3 - 2 * t); };

/* =====================================================================
   GARMENT PATTERN
   ---------------------------------------------------------------------
   The tee is cut like a real one: a FRONT and a BACK panel, each made of
   a body grid plus two sleeve halves, laid out in a 2D pattern plane
   (metres, origin at hem centre, +x = viewer's right when facing front).
   The panels are separate particle sets joined by zero-length seam
   constraints along the sides, shoulders and under/over-arm seams.
   Rest lengths come from the flat pattern, so the cloth "wants" to be
   the shape it was cut as, while the 3D drape is free to emerge.
   ===================================================================== */
const PAT = {
  W: 0.31,        // half chest width (boxy, oversized)
  Hs: 0.705,      // shoulder point height (dropped shoulder)
  Hn: 0.745,      // high-point-shoulder (neck side) height
  Nw: 0.100,      // half neck width
  dropF: 0.085,   // front neck drop
  dropB: 0.024,   // back neck drop
  nC: 40,         // body columns (segments)
  nR: 46,         // body rows (segments)
  jA: 28,         // armpit row
  nk: 15,         // sleeve segments along the arm
  theta: 28 * Math.PI / 180, // sleeve angle below horizontal
  Ltop: 0.24,     // over-arm sleeve length (ends near the elbow)
  cuffW: 0.21,    // flat sleeve opening width (wide sleeve)
  collarW: 0.026, // ribbed crew-neck band width
  hemW: 0.026,    // hem band width
  cuffB: 0.024,   // sleeve cuff band width
  zOff: 0.014,    // initial half-gap between front & back layers
};

/** Height of the top edge of the body at pattern x (neckline + shoulder slope). */
function topEdge(x, drop) {
  const ax = Math.abs(x);
  if (ax < PAT.Nw) { const t = ax / PAT.Nw; return PAT.Hn - drop * Math.pow(Math.max(0, 1 - t * t), 0.75); }
  return PAT.Hn + (PAT.Hs - PAT.Hn) * (ax - PAT.Nw) / (PAT.W - PAT.Nw);
}

function segDist(px, py, ax, ay, bx, by) {
  const dx = bx - ax, dy = by - ay, l2 = dx * dx + dy * dy;
  const t = l2 > 0 ? clamp(((px - ax) * dx + (py - ay) * dy) / l2, 0, 1) : 0;
  return { d: Math.hypot(px - ax - dx * t, py - ay - dy * t), t };
}

/**
 * Builds every static buffer the simulation and renderer need.
 * Returns typed arrays ready for upload plus a few index lists.
 */
function buildGarment() {
  const P = PAT, M = P.nR - P.jA;
  const A = P.Hs * P.jA / P.nR;
  const dir = [Math.cos(P.theta), -Math.sin(P.theta)], perp = [Math.sin(P.theta), Math.cos(P.theta)];
  const Pt = [P.W, P.Hs], Qt = [P.W, A];
  const P2 = [Pt[0] + P.Ltop * dir[0], Pt[1] + P.Ltop * dir[1]];
  const Q2 = [P2[0] - P.cuffW * perp[0], P2[1] - P.cuffW * perp[1]];

  const px = [], py = [], panelOf = [], regionOf = [];
  const bodyIdx = [[], []], slvIdx = [[[], []], [[], []]]; // [panel][side][k][m]
  const add = (x, y, panel, region) => { px.push(x); py.push(y); panelOf.push(panel); regionOf.push(region); return px.length - 1; };

  for (let p = 0; p < 2; p++) {
    const drop = p ? P.dropB : P.dropF;
    for (let i = 0; i <= P.nC; i++) {
      const x = -P.W + 2 * P.W * i / P.nC, top = topEdge(x, drop), col = [];
      for (let j = 0; j <= P.nR; j++) col.push(add(x, top * j / P.nR, p, 0));
      bodyIdx[p].push(col);
    }
    for (let s = 0; s < 2; s++) {           // s=0 right sleeve (+x), s=1 left sleeve
      const sx = s ? -1 : 1, grid = slvIdx[p][s];
      grid.push([]);
      for (let m = 0; m <= M; m++) grid[0].push(bodyIdx[p][s ? 0 : P.nC][P.jA + m]); // shared armhole column
      for (let k = 1; k <= P.nk; k++) {
        const t = k / P.nk, col = [];
        const bx = Qt[0] + (Q2[0] - Qt[0]) * t, by = Qt[1] + (Q2[1] - Qt[1]) * t;
        const tx = Pt[0] + (P2[0] - Pt[0]) * t, ty = Pt[1] + (P2[1] - Pt[1]) * t;
        for (let m = 0; m <= M; m++) { const u = m / M; col.push(add(sx * (bx + (tx - bx) * u), by + (ty - by) * u, p, 1)); }
        grid.push(col);
      }
    }
  }
  const N = px.length;

  // ---- seam polylines (pattern space, both sides) and per-vertex distance fields
  const seams = [];
  for (const sx of [1, -1]) {
    seams.push([sx * P.W, 0, sx * P.W, A], [sx * P.W, A, sx * P.W, P.Hs], [sx * P.Nw, P.Hn, sx * P.W, P.Hs],
      [sx * P.W, P.Hs, sx * P2[0], P2[1]], [sx * P.W, A, sx * Q2[0], Q2[1]]);
  }
  const neckLines = [0, 1].map((p) => {
    const pts = []; const drop = p ? P.dropB : P.dropF;
    for (let i = 0; i <= 48; i++) { const x = -P.Nw + 2 * P.Nw * i / 48; pts.push([x, topEdge(x, drop)]); }
    const cum = [0]; for (let i = 1; i < pts.length; i++) cum.push(cum[i - 1] + Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]));
    return { pts, cum };
  });
  const seamDist = new Float32Array(N), edgeDist = new Float32Array(N), neckDist = new Float32Array(N), ribCoord = new Float32Array(N);
  for (let v = 0; v < N; v++) {
    const x = px[v], y = py[v];
    let sd = 1e9; for (const s of seams) sd = Math.min(sd, segDist(x, y, s[0], s[1], s[2], s[3]).d);
    seamDist[v] = sd;
    if (regionOf[v] === 0) {
      edgeDist[v] = y;
      const nl = neckLines[panelOf[v]]; let best = 1e9, arc = 0;
      for (let i = 0; i < nl.pts.length - 1; i++) {
        const a = nl.pts[i], b = nl.pts[i + 1], r = segDist(x, y, a[0], a[1], b[0], b[1]);
        if (r.d < best) { best = r.d; arc = nl.cum[i] + r.t * (nl.cum[i + 1] - nl.cum[i]); }
      }
      neckDist[v] = best;
      ribCoord[v] = best < 0.08 ? arc : x;
    } else {
      const ux = Math.abs(x);
      edgeDist[v] = Math.abs((ux - P2[0]) * dir[0] + (y - P2[1]) * dir[1]);
      neckDist[v] = 1;
      ribCoord[v] = (ux - P2[0]) * perp[0] + (y - P2[1]) * perp[1];
    }
  }

  // ---- per-vertex material properties (mass, drag, stiffness multipliers)
  const invMass = new Float32Array(N), dragMul = new Float32Array(N), bendMul = new Float32Array(N), strMul = new Float32Array(N);
  for (let v = 0; v < N; v++) {
    let mass = 1, drag = 1, bend = 1, str = 1;
    if (regionOf[v] === 1) { mass = 0.72; drag = 1.45; bend = 0.55; }
    if (neckDist[v] < P.collarW) { mass = 1.5; bend = 7; str = 2.5; drag = 0.8; }          // thick ribbed collar
    else if (regionOf[v] === 0 && edgeDist[v] < P.hemW) { mass = 1.3; bend = 3.5; str = 1.6; } // folded hem band
    else if (regionOf[v] === 1 && edgeDist[v] < P.cuffB) { mass = 1.0; bend = 2.4; str = 1.4; } // sleeve cuff band
    invMass[v] = 1 / mass; dragMul[v] = drag; bendMul[v] = bend; strMul[v] = str;
  }

  // ---- constraints: structural, shear, bending, long-range tethers, seams
  // type ids: 0 structural, 1 shear, 2 bending, 3 tether (stretch-only), 4 seam weld
  const edges = new Map();
  const dist2D = (a, b) => Math.hypot(px[a] - px[b], py[a] - py[b]);
  const addEdge = (a, b, type) => {
    if (a === b || a === undefined || b === undefined) return;
    const key = a < b ? a * N + b : b * N + a;
    const prev = edges.get(key);
    if (prev !== undefined && prev.type <= type) return;
    const mul = type === 2 ? (bendMul[a] + bendMul[b]) * 0.5 : type <= 1 ? (strMul[a] + strMul[b]) * 0.5 : 1;
    edges.set(key, { a, b, type, rest: type === 4 ? 0 : dist2D(a, b), mul });
  };
  const tris = [], quads = [];
  const gridEdges = (g, nu, nv, tetherAlong, tetherFar) => {
    for (let u = 0; u <= nu; u++) for (let v = 0; v <= nv; v++) {
      const id = g[u][v];
      if (u < nu) addEdge(id, g[u + 1][v], 0);
      if (v < nv) addEdge(id, g[u][v + 1], 0);
      if (u < nu && v < nv) {
        addEdge(id, g[u + 1][v + 1], 1); addEdge(g[u + 1][v], g[u][v + 1], 1);
        quads.push([id, g[u + 1][v], g[u + 1][v + 1], g[u][v + 1], (u + v) & 1]);
      }
      if (u + 2 <= nu) addEdge(id, g[u + 2][v], 2);
      if (v + 2 <= nv) addEdge(id, g[u][v + 2], 2);
      for (const o of [tetherAlong, tetherFar]) {
        if (!o) continue;
        if (u + o <= nu) addEdge(id, g[u + o][v], 3);
        if (v + o <= nv) addEdge(id, g[u][v + o], 3);
      }
      const d = tetherAlong;
      if (u + d <= nu && v + d <= nv) addEdge(id, g[u + d][v + d], 3);
      if (u + d <= nu && v - d >= 0) addEdge(id, g[u + d][v - d], 3);
    }
  };
  for (let p = 0; p < 2; p++) {
    gridEdges(bodyIdx[p], P.nC, P.nR, 4, 12);
    for (let s = 0; s < 2; s++) {
      gridEdges(slvIdx[p][s], P.nk, M, 4, 0);
      // tethers across the armhole so sleeves can't over-stretch away from the body
      const bodyCol = s ? 4 : P.nC - 4;
      for (let m = 0; m <= M; m += 2) addEdge(slvIdx[p][s][4][m], bodyIdx[p][bodyCol][P.jA + m], 3);
    }
  }
  // seam pairs: identical (grid, u, v) locations in the front and back panels
  const partner = new Int32Array(N).fill(-1);
  const seamPair = (f, b) => { if (partner[f] >= 0) return; partner[f] = b; partner[b] = f; addEdge(f, b, 4); };
  for (let j = 0; j <= P.jA; j++) for (const i of [0, P.nC]) seamPair(bodyIdx[0][i][j], bodyIdx[1][i][j]);
  for (let i = 0; i <= P.nC; i++) if (Math.abs(px[bodyIdx[0][i][P.nR]]) >= P.Nw - 1e-6) seamPair(bodyIdx[0][i][P.nR], bodyIdx[1][i][P.nR]);
  for (let s = 0; s < 2; s++) for (let k = 1; k <= P.nk; k++) {
    seamPair(slvIdx[0][s][k][M], slvIdx[1][s][k][M]);
    seamPair(slvIdx[0][s][k][0], slvIdx[1][s][k][0]);
  }

  // ---- vertex-centric adjacency (each constraint is stored once per endpoint)
  const lists = Array.from({ length: N }, () => []);
  for (const e of edges.values()) { lists[e.a].push([e.b, e.rest, e.type, e.mul]); lists[e.b].push([e.a, e.rest, e.type, e.mul]); }
  const adjRange = new Uint32Array(N * 2);
  let total = 0; for (let v = 0; v < N; v++) total += lists[v].length;
  const adjBuf = new ArrayBuffer(total * 16), adjU = new Uint32Array(adjBuf), adjF = new Float32Array(adjBuf);
  let o = 0;
  for (let v = 0; v < N; v++) {
    adjRange[v * 2] = o; adjRange[v * 2 + 1] = lists[v].length;
    for (const [j, rest, type, mul] of lists[v]) { adjU[o * 4] = j; adjF[o * 4 + 1] = rest; adjU[o * 4 + 2] = type; adjF[o * 4 + 3] = mul; o++; }
  }

  // ---- triangles, oriented so the outside of the garment is front-facing (CCW)
  for (const [a, b, c, d, alt] of quads) {
    const area = (px[b] - px[a]) * (py[c] - py[a]) - (py[b] - py[a]) * (px[c] - px[a]);
    const flip = (area < 0) !== (panelOf[a] === 1);
    const q = flip ? [a, d, c, b] : [a, b, c, d];
    if (alt) tris.push(q[0], q[1], q[2], q[0], q[2], q[3]);
    else tris.push(q[0], q[1], q[3], q[1], q[2], q[3]);
  }

  // ---- normal-estimation neighbours (left, right, down, up) + rest spans for stretch
  const nbr = new Uint32Array(N * 4), phys = new Float32Array(N * 4);
  const setNbr = (id, l, r, d, u) => {
    const cr = (px[r] - px[l]) * (py[u] - py[d]) - (py[r] - py[l]) * (px[u] - px[d]);
    if (cr < 0) [l, r] = [r, l];
    nbr.set([l, r, d, u], id * 4);
    phys.set([invMass[id], dragMul[id], dist2D(l, r) || 1e-3, dist2D(d, u) || 1e-3], id * 4);
  };
  for (let p = 0; p < 2; p++) {
    const g = bodyIdx[p];
    for (let i = 0; i <= P.nC; i++) for (let j = 0; j <= P.nR; j++)
      setNbr(g[i][j], g[Math.max(i - 1, 0)][j], g[Math.min(i + 1, P.nC)][j], g[i][Math.max(j - 1, 0)], g[i][Math.min(j + 1, P.nR)]);
    for (let s = 0; s < 2; s++) {
      const q = slvIdx[p][s];
      for (let k = 1; k <= P.nk; k++) for (let m = 0; m <= M; m++)
        setNbr(q[k][m], q[k - 1][m], q[Math.min(k + 1, P.nk)][m], q[k][Math.max(m - 1, 0)], q[k][Math.min(m + 1, M)]);
    }
  }

  // ---- static render attributes and self-collision metadata
  const attr = new Float32Array(N * 8), meta = new Float32Array(N * 4);
  for (let v = 0; v < N; v++) {
    attr.set([px[v], py[v], seamDist[v], edgeDist[v], neckDist[v], ribCoord[v], regionOf[v], panelOf[v]], v * 8);
    meta.set([px[v], py[v], seamDist[v], panelOf[v]], v * 4);
  }

  // shoulder-seam vertices that sit on the hanger arms
  const hangerPins = [];
  for (let p = 0; p < 2; p++) for (let i = 0; i <= P.nC; i++) {
    const id = bodyIdx[p][i][P.nR], ax = Math.abs(px[id]);
    if (ax >= P.Nw - 1e-6 && ax <= 0.235) hangerPins.push(id);
  }

  return { N, px, py, panelOf, seamDist, partner, adjRange, adjBuf, adjCount: total, indices: new Uint32Array(tris),
    nbr, phys, attr, meta, hangerPins, spacing: 2 * P.W / P.nC };
}

/**
 * Initial particle positions for a given scene mode.
 * Layers start a few millimetres apart and meet exactly at the seams.
 */
function layoutShirt(g, mode) {
  const pos = new Float32Array(g.N * 4);
  const Y0 = 0.27;
  // free fall: tilt the shirt back and twist it a little so it lands and crumples naturally
  const tilt = mode === 'free' ? -1.05 : 0, yaw = mode === 'free' ? 0.45 : 0;
  const ct = Math.cos(tilt), st = Math.sin(tilt), cy = Math.cos(yaw), sy = Math.sin(yaw);
  for (let v = 0; v < g.N; v++) {
    let x = g.px[v], y = g.py[v];
    let z = (g.panelOf[v] ? -1 : 1) * PAT.zOff * smoothstep(0.0, 0.045, g.seamDist[v]);
    if (mode === 'free') {
      y -= 0.4; // rotate about the shirt's middle
      const y2 = y * ct - z * st, z2 = y * st + z * ct; y = y2; z = z2;
      const x3 = x * cy + z * sy, z3 = -x * sy + z * cy; x = x3; z = z3;
      y += 0.95;
    } else y += Y0;
    pos.set([x, y, z, 1], v * 4);
  }
  return pos;
}

/* =====================================================================
   WGSL: CLOTH SIMULATION (compute)
   ---------------------------------------------------------------------
   Position-based dynamics, vertex-centric Jacobi solver:
     integrate  -> predict positions from velocity, gravity, air, wind
     solve (xN) -> project distance constraints (structural / shear /
                   bending / stretch-only tethers / seam welds), XPBD-style
                   compliance so heavier fabric sags more, ping-pong buffers
     collide    -> floor (Coulomb friction), mannequin SDF, hanger bars
                   (fused into the end of every solve iteration)
     hash+self  -> spatial-hash particle self-collision
     normals    -> render positions (seam-welded), normals, stretch, fold AO
   Buffers are vec4-packed; "stat" and "ctrl" hold two vec4 per particle.
   ===================================================================== */
const HASH_SLOTS = 8;

const WGSL_SIM_COMMON = /* wgsl */`
struct Sim {
  dt: f32, time: f32, gravity: f32, drag: f32,
  kStretch: f32, kShear: f32, kBend: f32, kTether: f32,
  wind: vec4f,      // xyz wind velocity (m/s), w extra gust
  grab: vec4f,      // xyz hand target, w active
  grabQ: vec4f,     // twist quaternion applied to grabbed offsets
  impulse: vec4f,   // xyz shake acceleration, w phase
  manq: vec4f,      // x enabled, y growth 0..1
  hanger: vec4f,    // x enabled
  floorY: f32, friction: f32, radius: f32, count: u32,
  omega: f32, selfK: f32, cell: f32, hashMask: u32,
  massScale: f32, damping: f32, selfRadius: f32, skipDist: f32,
};
@group(0) @binding(0) var<uniform> sim: Sim;
const SLOTS: u32 = ${HASH_SLOTS}u;

fn cellHash(c: vec3i) -> u32 {
  let h = (bitcast<u32>(c.x) * 73856093u) ^ (bitcast<u32>(c.y) * 19349663u) ^ (bitcast<u32>(c.z) * 83492791u);
  return h & sim.hashMask;
}
fn qrot(q: vec4f, v: vec3f) -> vec3f {
  let t = 2.0 * cross(q.xyz, v);
  return v + q.w * t + cross(q.xyz, t);
}
`;

/* ---- integrate: forces + prediction (in place on current buffer) ---- */
const WGSL_INTEGRATE = WGSL_SIM_COMMON + /* wgsl */`
@group(0) @binding(1) var<storage, read_write> pos: array<vec4f>;
@group(0) @binding(2) var<storage, read_write> prev: array<vec4f>;
@group(0) @binding(3) var<storage, read> stat: array<vec4f>;
@group(0) @binding(4) var<storage, read> ctrl: array<vec4f>;
@group(0) @binding(5) var<storage, read> rnd: array<vec4f>;

fn turb(p: vec3f, t: f32) -> vec3f {
  return vec3f(sin(p.y * 5.1 + t * 2.3) + sin(p.z * 7.3 - t * 3.1),
               sin(p.x * 6.2 - t * 1.7) * 0.6,
               sin(p.x * 4.7 + t * 2.9) + sin(p.y * 6.9 + t * 1.3)) * 0.5;
}

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3u) {
  let i = gid.x;
  if (i >= sim.count) { return; }
  let pin = ctrl[2u * i];
  if (pin.w > 0.5) {                       // pinned: kinematic
    pos[i] = vec4f(pin.xyz, 0.0);
    prev[i] = vec4f(pin.xyz, 0.0);
    return;
  }
  let ph = stat[2u * i];
  let w = ph.x / sim.massScale;            // inverse mass (fabric weight slider)
  var p = pos[i].xyz;
  var v = (p - prev[i].xyz) / sim.dt;
  v *= exp(-sim.damping * sim.dt);

  var a = vec3f(0.0, -sim.gravity, 0.0);
  // relative air velocity, with gusty wind that travels across the cloth
  var air = sim.wind.xyz;
  let ws = length(air);
  if (ws > 0.0) {
    let wave = sin(dot(p, vec3f(3.1, 1.3, 2.2)) - sim.time * 6.0) * sin(sim.time * 0.83 + p.y * 1.7);
    air = air * (0.7 + 0.45 * wave + sim.wind.w) + turb(p * 1.3, sim.time) * ws * 0.45;
  }
  let rel = air - v;
  let n = normalize(rnd[2u * i + 1u].xyz + vec3f(0.0, 1e-5, 0.0));
  let vn = dot(rel, n);
  a += n * (vn * abs(vn)) * sim.drag * ph.y * w;   // quadratic pressure drag on the surface
  a += rel * 0.06 * ph.y * w;                       // light skin friction
  // shake: oscillating push that travels down the garment so it flaps
  a += sim.impulse.xyz * sin(sim.impulse.w + p.y * 8.0 + p.x * 5.0) * ph.y;

  v += a * sim.dt;
  prev[i] = vec4f(p, 0.0);
  p += v * sim.dt;
  pos[i] = vec4f(p, w);
}
`;

/* ---- colliders: floor (Coulomb friction), invisible mannequin, hanger ----
   Projected at the end of every Jacobi iteration (fused into the solver). */
const WGSL_COLLIDERS = /* wgsl */`
fn sdEllipsoid(p: vec3f, r: vec3f) -> f32 {
  let k0 = length(p / r);
  let k1 = length(p / (r * r));
  return k0 * (k0 - 1.0) / max(k1, 1e-6);
}
fn sdCapsule(p: vec3f, a: vec3f, b: vec3f, r: f32) -> f32 {
  let pa = p - a; let ba = b - a;
  let h = clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0);
  return length(pa - ba * h) - r;
}
fn smin(a: f32, b: f32, k: f32) -> f32 {
  let h = max(k - abs(a - b), 0.0) / k;
  return min(a, b) - h * h * k * 0.25;
}
// Invisible mannequin torso. The depth axis "inflates" on entry so the
// flat-laid shirt is gently filled out instead of exploding outward.
fn torso(p0: vec3f) -> f32 {
  let g = mix(0.12, 1.0, sim.manq.y);
  let p = vec3f(p0.x, p0.y, p0.z / g);
  let chest = sdEllipsoid(p - vec3f(0.0, 0.70, 0.0), vec3f(0.178, 0.25, 0.115));
  let waist = sdEllipsoid(p - vec3f(0.0, 0.42, 0.0), vec3f(0.152, 0.26, 0.098));
  let hips  = sdEllipsoid(p - vec3f(0.0, 0.16, 0.0), vec3f(0.168, 0.22, 0.108));
  // sloping shoulders (left/right) so the dropped shoulder seam drapes naturally
  let sh    = min(sdCapsule(p, vec3f(-0.05, 0.93, 0.0), vec3f(-0.178, 0.884, 0.0), 0.058),
                  sdCapsule(p, vec3f(0.05, 0.93, 0.0), vec3f(0.178, 0.884, 0.0), 0.058));
  let neck  = sdCapsule(p, vec3f(0.0, 0.93, -0.012), vec3f(0.0, 1.16, -0.012), 0.056);
  var d = smin(chest, waist, 0.10);
  d = smin(d, hips, 0.10);
  d = smin(d, sh, 0.08);
  d = smin(d, neck, 0.03);
  return d * g;
}
fn hangerSDF(p: vec3f) -> f32 {
  let c = vec3f(0.0, 1.006, 0.0);
  let a = sdCapsule(p, c, vec3f(0.232, 0.968, 0.0), 0.011);
  let b = sdCapsule(p, c, vec3f(-0.232, 0.968, 0.0), 0.011);
  return min(a, b);
}

fn collide(p0: vec3f, pp: vec3f) -> vec3f {
  var p = p0;
  let r = sim.radius;

  if (sim.manq.x > 0.5) {
    let d = torso(p);
    if (d < r) {
      let e = vec2f(1.0, -1.0) * 0.0015;
      let n = normalize(e.xyy * torso(p + e.xyy) + e.yyx * torso(p + e.yyx) + e.yxy * torso(p + e.yxy) + e.xxx * torso(p + e.xxx));
      let pen = r - d;
      p += n * pen;
      let dx = p - pp; let tang = dx - n * dot(dx, n); let tl = length(tang);
      if (tl > 1e-9) { p -= tang * min(1.0, 0.6 * pen / tl); }
    }
  }
  if (sim.hanger.x > 0.5) {
    let d = hangerSDF(p);
    if (d < r) {
      let e = vec2f(1.0, -1.0) * 0.001;
      let n = normalize(e.xyy * hangerSDF(p + e.xyy) + e.yyx * hangerSDF(p + e.yyx) + e.yxy * hangerSDF(p + e.yxy) + e.xxx * hangerSDF(p + e.xxx));
      p += n * (r - d);
    }
  }
  // floor with Coulomb friction: tangential motion is limited by mu * penetration
  let fy = sim.floorY + r;
  if (p.y < fy) {
    let pen = fy - p.y;
    p.y = fy;
    let dx = vec3f(p.x - pp.x, 0.0, p.z - pp.z);
    let tl = length(dx);
    if (tl > 1e-9) { p -= dx * min(1.0, sim.friction * pen / tl); }
  }
  return p;
}
`;

/* ---- solve: one Jacobi iteration over every particle's constraints ---- */
const WGSL_SOLVE = WGSL_SIM_COMMON + WGSL_COLLIDERS + /* wgsl */`
@group(0) @binding(1) var<storage, read> posIn: array<vec4f>;
@group(0) @binding(2) var<storage, read_write> posOut: array<vec4f>;
@group(0) @binding(3) var<storage, read> adjRange: array<vec2u>;
@group(0) @binding(4) var<storage, read> adj: array<vec4u>;
@group(0) @binding(5) var<storage, read> ctrl: array<vec4f>;
@group(0) @binding(6) var<storage, read> prev: array<vec4f>;

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3u) {
  let i = gid.x;
  if (i >= sim.count) { return; }
  let me = posIn[i];
  let wi = me.w;
  if (wi == 0.0) { posOut[i] = me; return; }
  var p = me.xyz;
  let r = adjRange[i];
  var corr = vec3f(0.0);
  var ksum = 0.0;
  for (var e = r.x; e < r.x + r.y; e++) {
    let c = adj[e];
    let o = posIn[c.x];
    let d = p - o.xyz;
    let len = length(d);
    let rest = bitcast<f32>(c.y);
    let C = len - rest;
    if (len < 1e-7 || (c.z == 3u && C <= 0.0)) { continue; } // tethers only resist stretch
    var comp = sim.kStretch;
    if (c.z == 1u) { comp = sim.kShear; }
    else if (c.z == 2u) { comp = sim.kBend; }
    else if (c.z == 3u) { comp = sim.kTether; }
    else if (c.z == 4u) { comp = 0.0; }
    comp = comp / bitcast<f32>(c.w);
    let wsum = wi + o.w;
    let denom = wsum + comp;
    corr -= (wi * C / denom) * (d / len);
    ksum += wsum / denom;
  }
  p += corr * (sim.omega / max(ksum, 1.0));

  // grabbed patch follows the hand (soft, so the rest of the cloth lags behind)
  if (sim.grab.w > 0.5) {
    let g = ctrl[2u * i + 1u];
    if (g.w > 0.0) {
      let tgt = sim.grab.xyz + qrot(sim.grabQ, g.xyz);
      p = mix(p, tgt, g.w);
    }
  }
  posOut[i] = vec4f(collide(p, prev[i].xyz), wi);
}
`;

/* ---- spatial hash: clear + insert ---- */
const WGSL_HASH_CLEAR = WGSL_SIM_COMMON + /* wgsl */`
@group(0) @binding(1) var<storage, read_write> hashCount: array<u32>;
@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3u) {
  if (gid.x <= sim.hashMask) { hashCount[gid.x] = 0u; }
}
`;
const WGSL_HASH_INSERT = WGSL_SIM_COMMON + /* wgsl */`
@group(0) @binding(1) var<storage, read> pos: array<vec4f>;
@group(0) @binding(2) var<storage, read_write> hashCount: array<atomic<u32>>;
@group(0) @binding(3) var<storage, read_write> hashCells: array<u32>;
@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3u) {
  let i = gid.x;
  if (i >= sim.count) { return; }
  let h = cellHash(vec3i(floor(pos[i].xyz / sim.cell)));
  let slot = atomicAdd(&hashCount[h], 1u);
  if (slot < SLOTS) { hashCells[h * SLOTS + slot] = i; }
}
`;

/* ---- self-collision: push apart particles closer than the cloth thickness ---- */
const WGSL_SELF = WGSL_SIM_COMMON + /* wgsl */`
@group(0) @binding(1) var<storage, read> posIn: array<vec4f>;
@group(0) @binding(2) var<storage, read_write> posOut: array<vec4f>;
@group(0) @binding(3) var<storage, read> stat: array<vec4f>;
@group(0) @binding(4) var<storage, read> hashCount: array<u32>;
@group(0) @binding(5) var<storage, read> hashCells: array<u32>;

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3u) {
  let i = gid.x;
  if (i >= sim.count) { return; }
  let me = posIn[i];
  if (me.w == 0.0) { posOut[i] = me; return; }
  let p = me.xyz;
  let mi = stat[2u * i + 1u];            // pattern x, y, seam distance, panel
  let c0 = vec3i(floor(p / sim.cell));
  let diam = 2.0 * sim.selfRadius;
  var corr = vec3f(0.0);
  var cnt = 0.0;
  for (var z = -1; z <= 1; z++) {
    for (var y = -1; y <= 1; y++) {
      for (var x = -1; x <= 1; x++) {
        let h = cellHash(c0 + vec3i(x, y, z));
        let n = min(hashCount[h], SLOTS);
        for (var s = 0u; s < n; s++) {
          let j = hashCells[h * SLOTS + s];
          if (j == i) { continue; }
          let d = p - posIn[j].xyz;
          let d2 = dot(d, d);
          if (d2 >= diam * diam || d2 < 1e-14) { continue; }
          // skip particles that are neighbours along the cloth surface
          let mj = stat[2u * j + 1u];
          var geo = distance(mi.xy, mj.xy);
          if (mi.w != mj.w) { geo += mi.z + mj.z; }
          if (geo < sim.skipDist) { continue; }
          let dist = sqrt(d2);
          corr += d * ((diam - dist) * 0.5 / dist);
          cnt += 1.0;
        }
      }
    }
  }
  posOut[i] = vec4f(p + corr * (sim.selfK / max(cnt * 0.5, 1.0)), me.w);
}
`;

/* ---- normals: welded render positions, smooth normals, stretch & fold cavity ---- */
const WGSL_NORMALS = WGSL_SIM_COMMON + /* wgsl */`
@group(0) @binding(1) var<storage, read> pos: array<vec4f>;
@group(0) @binding(2) var<storage, read> stat: array<vec4f>;
@group(0) @binding(3) var<storage, read> nbr: array<vec4u>;
@group(0) @binding(4) var<storage, read> partner: array<i32>;
@group(0) @binding(5) var<storage, read_write> rnd: array<vec4f>;

fn P(i: u32) -> vec3f {
  let q = partner[i];
  if (q >= 0) { return 0.5 * (pos[i].xyz + pos[u32(q)].xyz); } // seams render watertight
  return pos[i].xyz;
}

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3u) {
  let i = gid.x;
  if (i >= sim.count) { return; }
  let nb = nbr[i];
  let p = P(i);
  let l = P(nb.x); let r = P(nb.y); let d = P(nb.z); let u = P(nb.w);
  let ph = stat[2u * i];
  let panel = stat[2u * i + 1u].w;
  var n = cross(r - l, u - d);
  if (panel > 0.5) { n = -n; }
  n = normalize(n + vec3f(0.0, 0.0, 1e-9));
  let stretch = max(length(r - l) / ph.z, length(u - d) / ph.w);
  // two-scale cavity: how far the neighbourhood sits "above" the surface (folds/creases)
  let ll = P(nbr[nb.x].x); let rr = P(nbr[nb.y].y); let dd = P(nbr[nb.z].z); let uu = P(nbr[nb.w].w);
  let c1 = dot(0.25 * (l + r + d + u) - p, n) / (0.25 * (ph.z + ph.w));
  let c2 = dot(0.25 * (ll + rr + dd + uu) - p, n) / (0.5 * (ph.z + ph.w));
  rnd[2u * i] = vec4f(p, c1 * 0.6 + c2 * 0.8);
  rnd[2u * i + 1u] = vec4f(n, stretch);
}
`;

/* =====================================================================
   WGSL: RENDERING
   ---------------------------------------------------------------------
   Camera-relative studio rig (key, fill, two rims), shadow-mapped key
   light, bottom-up "contact" height map for floor AO, procedural cotton
   (baked wash/slub noise, analytic jersey knit, rib, double-needle stitching)
   and a raised soft-hand print that cracks when the fabric is stretched.
   ===================================================================== */
const WGSL_CAM = /* wgsl */`
struct Cam {
  viewProj: mat4x4f,
  invViewProj: mat4x4f,
  lightVP: mat4x4f,
  aoVP: mat4x4f,
  eye: vec4f,
  fabric: vec4f,     // rgb linear base colour, w wash strength
  fuzz: vec4f,       // rgb fuzz/sheen colour, w thread lightness
  frontRect: vec4f,  // print placement in pattern metres: cx, cy, w, h
  backRect: vec4f,
  misc: vec4f,       // x time, y shadow texel, z exposure, w floor y
  res: vec4f,        // width, height, 1/width, 1/height
  keyDir: vec4f,
  fillDir: vec4f,
  rimL: vec4f,
  rimR: vec4f,
  ao: vec4f,         // x eye y of AO camera, y depth range, z texture size, w world half-size
};
@group(0) @binding(0) var<uniform> cam: Cam;

fn aces(x: vec3f) -> vec3f {
  return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), vec3f(0.0), vec3f(1.0));
}
fn hash21(p: vec2f) -> f32 {
  var q = fract(p * vec2f(123.34, 456.21));
  q += dot(q, q + 45.32);
  return fract(q.x * q.y);
}
// Backdrop: soft product-photo gradient with a gentle vignette (linear colour)
fn backdrop(uv: vec2f) -> vec3f {
  var c = mix(vec3f(0.80, 0.805, 0.82), vec3f(0.62, 0.625, 0.645), smoothstep(0.0, 1.0, uv.y));
  let d = length((uv - vec2f(0.5, 0.4)) * vec2f(cam.res.x * cam.res.w, 1.0));
  c *= 1.0 - 0.2 * smoothstep(0.35, 1.25, d);
  return c;
}
fn dither(fc: vec2f) -> f32 { return (hash21(fc) - 0.5) / 255.0; }
`;

const WGSL_LIGHT = /* wgsl */`
@group(0) @binding(6) var shadowMap: texture_depth_2d;
@group(0) @binding(7) var shadowSamp: sampler_comparison;

var<private> POISSON: array<vec2f, 12> = array<vec2f, 12>(
  vec2f(-0.326, -0.406), vec2f(-0.840, -0.074), vec2f(-0.696, 0.457), vec2f(-0.203, 0.621),
  vec2f(0.962, -0.195), vec2f(0.473, -0.480), vec2f(0.519, 0.767), vec2f(0.185, -0.893),
  vec2f(0.507, 0.064), vec2f(0.896, 0.412), vec2f(-0.322, -0.933), vec2f(-0.792, -0.598));

fn shadowAt(world: vec3f, N: vec3f, soft: f32, taps: i32) -> f32 {
  let lp = cam.lightVP * vec4f(world + N * 0.006, 1.0);
  let uv = lp.xy * vec2f(0.5, -0.5) + 0.5;
  if (any(uv < vec2f(0.0)) || any(uv > vec2f(1.0)) || lp.z > 1.0) { return 1.0; }
  let z = lp.z - 0.0012;
  let r = cam.misc.y * soft;
  var s = 0.0;
  for (var i = 0; i < taps; i++) { s += textureSampleCompareLevel(shadowMap, shadowSamp, uv + POISSON[i] * r, z); }
  return s / f32(taps);
}

fn ggx(NdH: f32, a: f32) -> f32 {
  let a2 = a * a; let d = NdH * NdH * (a2 - 1.0) + 1.0;
  return a2 / (3.14159 * d * d);
}
// Charlie sheen distribution: the soft fibre glow of brushed cotton
fn charlie(NdH: f32, r: f32) -> f32 {
  let inv = 1.0 / r; let s2 = max(1.0 - NdH * NdH, 0.0078125);
  return (2.0 + inv) * pow(s2, inv * 0.5) / 6.2831;
}
fn oneLight(N: vec3f, V: vec3f, L: vec3f, col: vec3f, alb: vec3f, rough: f32, f0: f32, sheen: vec3f, wrap: f32) -> vec3f {
  let NdL = dot(N, L);
  let nl = max(NdL, 0.0);
  let NdV = max(dot(N, V), 1e-3);
  let H = normalize(L + V);
  let NdH = max(dot(N, H), 0.0);
  let VdH = max(dot(V, H), 0.0);
  let diff = max((NdL + wrap) / (1.0 + wrap), 0.0);
  let F = f0 + (1.0 - f0) * pow(1.0 - VdH, 5.0);
  let spec = ggx(NdH, rough * rough) * F * 0.25 / max(NdV, 0.15) * nl;
  let sh = sheen * charlie(NdH, 0.55) / (4.0 * (nl + NdV - nl * NdV) + 1e-3) * nl;
  return col * (alb * diff + spec + sh);
}
// Full studio rig. Rims are placed behind the subject relative to the camera,
// so the black fabric always separates from the backdrop.
fn studio(N: vec3f, V: vec3f, alb: vec3f, rough: f32, f0: f32, sheen: vec3f, sh: f32, ao: f32) -> vec3f {
  var c = oneLight(N, V, cam.keyDir.xyz, vec3f(1.0, 0.965, 0.92) * 1.75 * sh, alb, rough, f0, sheen, 0.25);
  c += oneLight(N, V, cam.fillDir.xyz, vec3f(0.85, 0.9, 1.0) * 0.42, alb, rough, f0, sheen, 0.5) * mix(0.6, 1.0, ao);
  c += oneLight(N, V, cam.rimL.xyz, vec3f(1.0) * 2.1, alb, rough, f0, sheen, 0.0) * mix(0.5, 1.0, ao);
  c += oneLight(N, V, cam.rimR.xyz, vec3f(0.95, 0.97, 1.0) * 1.7, alb, rough, f0, sheen, 0.0) * mix(0.5, 1.0, ao);
  // hemisphere ambient (bright studio sweep above, darker floor bounce below)
  let hemi = mix(vec3f(0.42, 0.42, 0.43), vec3f(0.95, 0.96, 0.98), N.y * 0.5 + 0.5);
  c += hemi * alb * ao * 0.42;
  // fibre fuzz: soft light caught by the nap at grazing angles
  let fz = pow(1.0 - max(dot(N, V), 0.0), 3.0);
  c += sheen * fz * ao * (0.3 + 0.9 * max(dot(-V, cam.rimL.xyz), 0.0) + 0.6 * max(dot(-V, cam.rimR.xyz), 0.0));
  return c;
}
`;

/* ---- backdrop + floor in one fullscreen pass ----
   The floor is invisible except for the shadows it receives, so it is shaded
   analytically (ray/plane) here instead of as separate geometry. Cheap probes
   skip the soft-shadow and contact-AO loops wherever the floor is fully lit. */
const WGSL_BG = WGSL_CAM + WGSL_LIGHT + /* wgsl */`
@group(0) @binding(1) var aoMap: texture_depth_2d;
struct BOut { @builtin(position) pos: vec4f, @location(0) ndc: vec2f };
@vertex fn vs(@builtin(vertex_index) i: u32) -> BOut {
  let p = vec2f(f32((i << 1u) & 2u), f32(i & 2u)) * 2.0 - 1.0;
  var o: BOut; o.pos = vec4f(p, 1.0, 1.0); o.ndc = p;
  return o;
}
fn clothHeight(xz: vec2f) -> f32 {        // lowest cloth height above the floor at xz
  let hs = cam.ao.w; let size = cam.ao.z;
  let t = (xz / hs) * vec2f(0.5, -0.5) + 0.5;
  if (any(t < vec2f(0.0)) || any(t > vec2f(1.0))) { return 9.0; }
  let d = textureLoad(aoMap, vec2i(t * (size - 1.0)), 0);
  if (d >= 0.9999) { return 9.0; }
  return cam.ao.x + d * cam.ao.y - cam.misc.w;
}
fn floorShadow(world: vec3f) -> f32 {
  let lp = cam.lightVP * vec4f(world, 1.0);
  let uv = lp.xy * vec2f(0.5, -0.5) + 0.5;
  if (any(uv < vec2f(0.0)) || any(uv > vec2f(1.0)) || lp.z > 1.0) { return 1.0; }
  let z = lp.z - 0.002; let r = cam.misc.y * 7.0;
  var s = 0.0;
  for (var i = 0; i < 4; i++) { s += textureSampleCompareLevel(shadowMap, shadowSamp, uv + POISSON[i * 3] * r * 1.15, z); }
  if (s > 3.99) { return 1.0; }
  for (var i = 0; i < 12; i++) { s += textureSampleCompareLevel(shadowMap, shadowSamp, uv + POISSON[i] * r, z); }
  return s / 16.0;
}
@fragment fn fs(in: BOut) -> @location(0) vec4f {
  let uv = in.pos.xy * cam.res.zw;
  var col = backdrop(uv);
  let a = cam.invViewProj * vec4f(in.ndc, 0.0, 1.0);
  let b = cam.invViewProj * vec4f(in.ndc, 1.0, 1.0);
  let o = a.xyz / a.w; let d = normalize(b.xyz / b.w - o);
  if (d.y < -1e-4) {
    let w = o + d * ((cam.misc.w - o.y) / d.y);
    let rr = length(w.xz);
    if (rr < 3.2) {
      let sh = floorShadow(w);
      // contact occlusion: darker where cloth hovers just above the floor, softer as it rises
      var occ = 0.0;
      let probe = min(min(clothHeight(w.xz + vec2f(0.06, 0.0)), clothHeight(w.xz - vec2f(0.06, 0.0))),
                      min(clothHeight(w.xz + vec2f(0.0, 0.06)), clothHeight(w.xz - vec2f(0.0, 0.06))));
      if (min(probe, clothHeight(w.xz)) < 0.6) {
        for (var i = 0; i < 8; i++) { occ += exp(-max(clothHeight(w.xz + POISSON[i] * 0.045), 0.0) / 0.07); }
        occ /= 8.0;
      }
      let fade = 1.0 - smoothstep(1.6, 3.2, rr);
      col *= mix(1.0, mix(0.8, 1.0, sh) * (1.0 - 0.5 * occ), fade);
    }
  }
  return vec4f(pow(col, vec3f(1.0 / 2.2)) + dither(in.pos.xy), 1.0);
}
`;

/* ---- shadow / AO depth pass: cloth only ---- */
const WGSL_DEPTH = /* wgsl */`
@group(0) @binding(0) var<uniform> lvp: mat4x4f;
@group(0) @binding(1) var<storage, read> rnd: array<vec4f>;
@vertex fn vs(@builtin(vertex_index) vi: u32) -> @builtin(position) vec4f {
  return lvp * vec4f(rnd[2u * vi].xyz, 1.0);
}
`;

/* ---- the shirt ---- */
const WGSL_SHIRT = WGSL_CAM + WGSL_LIGHT + /* wgsl */`
@group(0) @binding(1) var<storage, read> rnd: array<vec4f>;
@group(0) @binding(2) var<storage, read> attr: array<vec4f>;
@group(0) @binding(3) var frontTex: texture_2d<f32>;
@group(0) @binding(4) var backTex: texture_2d<f32>;
@group(0) @binding(5) var linSamp: sampler;
@group(0) @binding(8) var detailTex: texture_2d<f32>;   // baked wash / streak / slub / crack cells
@group(0) @binding(9) var repSamp: sampler;

const COLLAR_W: f32 = ${PAT.collarW};
const HEM_W: f32 = ${PAT.hemW};
const CUFF_W: f32 = ${PAT.cuffB};

struct VOut {
  @builtin(position) pos: vec4f,
  @location(0) world: vec3f,
  @location(1) n: vec3f,
  @location(2) a0: vec4f,   // pattern x, y, seam distance, hem/cuff distance
  @location(3) a1: vec4f,   // neck distance, rib coordinate, region, panel
  @location(4) ex: vec2f,   // fold cavity, stretch
};
@vertex fn vs(@builtin(vertex_index) vi: u32) -> VOut {
  let p = rnd[2u * vi]; let n = rnd[2u * vi + 1u];
  var o: VOut;
  o.pos = cam.viewProj * vec4f(p.xyz, 1.0);
  o.world = p.xyz; o.n = n.xyz;
  o.a0 = attr[2u * vi]; o.a1 = attr[2u * vi + 1u];
  o.ex = vec2f(p.w, n.w);
  return o;
}

fn ridge(d: f32, c: f32, w: f32, fw: f32) -> vec2f {   // thread profile + derivative, anti-aliased
  let we = max(w, fw * 0.7);
  let x = (d - c) / we; let e = exp(-x * x) * (w / we);
  return vec2f(e, -2.0 * x / we * e);
}
fn knitH(q: vec2f) -> f32 {     // jersey: columns of interlocking V loops
  return 0.5 + 0.5 * sin(6.2831 * (q.y + abs(fract(q.x) - 0.5))) * (0.65 + 0.35 * sin(6.2831 * q.x));
}
fn inRect(t: vec2f) -> f32 { return f32(all(t >= vec2f(0.0)) && all(t <= vec2f(1.0))); }

@fragment fn fs(in: VOut, @builtin(front_facing) ff: bool) -> @location(0) vec4f {
  let uv = in.a0.xy;
  let seamD = in.a0.z; let edgeD = in.a0.w; let neckD = in.a1.x; let ribC = in.a1.y;
  let sleeve = in.a1.z > 0.5; let back = in.a1.w > 0.5;

  // derivatives first (must be in uniform control flow)
  let dPdx = dpdx(in.world); let dPdy = dpdy(in.world);
  let duvdx = dpdx(uv); let duvdy = dpdy(uv);
  let fwS = fwidth(seamD); let fwE = fwidth(edgeD); let fwN = fwidth(neckD); let fwR = fwidth(ribC);
  let dsx = dpdx(seamD); let dsy = dpdy(seamD); let dex = dpdx(edgeD); let dey = dpdy(edgeD);
  let dnx = dpdx(neckD); let dny = dpdy(neckD); let drx = dpdx(ribC); let dry = dpdy(ribC);
  let pxm = max(length(duvdx), length(duvdy)); // metres of cloth per pixel

  // ---- prints (sampled unconditionally, masked afterwards)
  let fr = cam.frontRect; let br = cam.backRect;
  let fuv = vec2f((uv.x - fr.x) / fr.z + 0.5, 0.5 - (uv.y - fr.y) / fr.w);
  let buv = vec2f(0.5 - (uv.x - br.x) / br.z, 0.5 - (uv.y - br.y) / br.w);
  let fgx = dpdx(fuv); let fgy = dpdy(fuv); let bgx = dpdx(buv); let bgy = dpdy(buv);
  // baked detail lookups (uniform control flow)
  let dW = textureSample(detailTex, repSamp, uv * 0.55 + select(vec2f(0.0), vec2f(0.37, 0.61), back));
  let dS = textureSample(detailTex, repSamp, uv * vec2f(1.15, 3.8));
  let dL = textureSample(detailTex, repSamp, uv * vec2f(2.2, 9.4));
  let dC = textureSample(detailTex, repSamp, uv * 13.0);
  let outside = f32(ff) * f32(!sleeve);
  let mF = inRect(fuv) * f32(!back) * outside;
  let mB = inRect(buv) * f32(back) * outside;
  var pa = 0.0; var pc = vec3f(0.0); var g = vec2f(0.0);
  if (mF > 0.5) {
    let fd = 1.5 / vec2f(textureDimensions(frontTex));
    let c = textureSampleGrad(frontTex, linSamp, fuv, fgx, fgy);
    let ax = textureSampleGrad(frontTex, linSamp, fuv + vec2f(fd.x, 0.0), fgx, fgy).a;
    let ay = textureSampleGrad(frontTex, linSamp, fuv + vec2f(0.0, fd.y), fgx, fgy).a;
    pa = c.a; pc = c.rgb;
    g = vec2f((ax - c.a) / fd.x / fr.z, -(ay - c.a) / fd.y / fr.w);
  } else if (mB > 0.5) {
    let bd = 1.5 / vec2f(textureDimensions(backTex));
    let c = textureSampleGrad(backTex, linSamp, buv, bgx, bgy);
    let ax = textureSampleGrad(backTex, linSamp, buv + vec2f(bd.x, 0.0), bgx, bgy).a;
    let ay = textureSampleGrad(backTex, linSamp, buv + vec2f(0.0, bd.y), bgx, bgy).a;
    pa = c.a; pc = c.rgb;
    g = vec2f(-(ax - c.a) / bd.x / br.z, -(ay - c.a) / bd.y / br.w);
  }
  g *= 0.00018;   // the ink layer is raised ~0.18 mm
  var hx = 0.0; var hy = 0.0;

  // ---- cotton: vintage wash, slub, knit
  var alb = cam.fabric.rgb;
  let wash = dW.r;
  let streak = dS.g;
  alb *= 1.0 + cam.fabric.w * ((wash - 0.5) * 0.85 + (streak - 0.5) * 0.4);
  let wear = max(max(1.0 - smoothstep(0.0, 0.014, seamD), 1.0 - smoothstep(0.0, 0.01, edgeD)), 1.0 - smoothstep(0.0, 0.007, neckD));
  alb = mix(alb, min(alb * 1.55 + 0.006, vec3f(1.0)), clamp(wear * cam.fabric.w * (0.4 + streak), 0.0, 1.0));
  alb *= 0.965 + 0.07 * dL.b;                                             // horizontal slub yarn
  let kf = 1.0 - smoothstep(0.0005, 0.0012, pxm);                        // knit only when zoomed in
  var k0 = 0.5;
  if (kf > 0.0) {
    let ks = vec2f(1.0 / 0.0022, 1.0 / 0.0017);
    let kq = uv * ks;
    k0 = knitH(kq);
    g += vec2f((knitH(kq + vec2f(0.04, 0.0)) - k0) / 0.04 * ks.x, (knitH(kq + vec2f(0.0, 0.04)) - k0) / 0.04 * ks.y) * 0.00010 * kf;
    alb *= 1.0 + (k0 - 0.5) * 0.14 * kf;
  }

  // Detail below is only evaluated near seams, bands and edges (most pixels skip it).
  let dashC = uv.x + uv.y;
  let dash = mix(0.8, 0.55 + 0.45 * smoothstep(-0.2, 0.4, sin(dashC * 6.2831 / 0.0034)), 1.0 - smoothstep(0.3, 0.7, fwidth(dashC) / 0.0034));
  let th = 0.00035 * dash;
  var thread = 0.0;

  // ---- ribbed crew neck + collar join (double-needle neck tape)
  if (!sleeve && neckD < COLLAR_W + 0.014) {
    let collar = 1.0 - smoothstep(COLLAR_W - 0.001, COLLAR_W + 0.0005, neckD);
    let ribP = 0.0046;
    let rf = 1.0 - smoothstep(0.3, 0.65, fwR / ribP);
    let rph = ribC * 6.2831 / ribP;
    let ribH = 0.5 + 0.5 * cos(rph);
    let ribD = -0.5 * sin(rph) * 6.2831 / ribP * 0.0007 * collar * rf;
    hx += ribD * drx; hy += ribD * dry;
    alb *= mix(1.0, 0.78 + 0.34 * ribH, collar * mix(0.35, 1.0, rf));
    let cs = ridge(neckD, COLLAR_W, 0.0016, fwN);                         // band sits proud of the body
    let c1 = ridge(neckD, COLLAR_W + 0.0035, 0.0006, fwN); let c2 = ridge(neckD, COLLAR_W + 0.0095, 0.0006, fwN);
    thread += c1.x + c2.x;
    let k = cs.y * 0.0006 + (c1.y + c2.y) * th;
    hx += k * dnx; hy += k * dny;
  }

  // ---- folded hem / cuff band with twin-needle coverstitch
  let bandW = select(HEM_W, CUFF_W, sleeve);
  if (edgeD < bandW + 0.006) {
    let hb = ridge(edgeD, bandW, 0.0018, fwE);
    let edgeRoll = ridge(edgeD, 0.0, 0.003, fwE);                        // rolled fold at the very edge
    let h1 = ridge(edgeD, bandW - 0.0045, 0.0006, fwE); let h2 = ridge(edgeD, bandW + 0.0018, 0.0006, fwE);
    thread += h1.x + h2.x;
    let k = hb.y * 0.0005 + edgeRoll.y * 0.0008 + (h1.y + h2.y) * th;
    hx += k * dex; hy += k * dey;
  }

  // ---- double-needle seams (shoulders, sides, armholes, sleeves)
  var seamShadow = 1.0;
  if (seamD < 0.016) {
    let s1 = ridge(seamD, 0.0055, 0.0006, fwS); let s2 = ridge(seamD, 0.0115, 0.0006, fwS);
    thread += s1.x + s2.x;
    let k = (s1.y + s2.y) * th;
    hx += k * dsx; hy += k * dsy;
    seamShadow = 1.0 - 0.35 * (1.0 - smoothstep(0.0, 0.003 + fwS, seamD));
  }
  thread = clamp(thread * dash, 0.0, 1.0);
  alb = mix(alb, alb * 1.25 + cam.fuzz.w, thread * 0.85) * seamShadow;

  // ---- print: soft-hand ink that cracks under stretch
  let stretch = in.ex.y;
  let crackLine = (1.0 - smoothstep(0.04, 0.14, dC.a)) * (1.0 - smoothstep(0.0007, 0.002, pxm));
  let crackAmt = 0.12 + 0.85 * smoothstep(1.03, 1.16, stretch);
  pa *= 1.0 - crackLine * crackAmt;
  g *= 1.0 - crackLine * 0.6;
  let ink = pc * (0.93 + 0.07 * k0) * mix(1.0, 0.94, wash);              // ink takes on the knit & wash
  let albedo = mix(alb, ink, pa);

  // ---- perturbed normal (surface-gradient bump mapping, no tangents needed)
  var N = normalize(in.n);
  if (!ff) { N = -N; }
  let dhdx = dot(g, duvdx) + hx; let dhdy = dot(g, duvdy) + hy;
  let R1 = cross(dPdy, N); let R2 = cross(N, dPdx); let det = dot(dPdx, R1);
  if (abs(det) > 1e-14) { N = normalize(abs(det) * N - sign(det) * (dhdx * R1 + dhdy * R2)); }

  // ---- lighting
  let V = normalize(cam.eye.xyz - in.world);
  let fold = clamp(1.0 - max(in.ex.x, 0.0) * 0.6, 0.3, 1.0) * clamp(1.0 + min(in.ex.x, 0.0) * 0.15, 0.85, 1.0);
  let ao = fold * select(0.32, 1.0, ff);                                  // inside of the shirt is dark
  let sh = shadowAt(in.world, N, 1.3, 5);
  let rough = mix(0.86, 0.52, pa);
  let f0 = mix(0.03, 0.05, pa);
  let sheen = cam.fuzz.rgb * mix(1.0, 0.35, pa) * select(0.5, 1.0, ff);
  let col = studio(N, V, albedo, rough, f0, sheen, sh, ao);
  return vec4f(pow(aces(col * cam.misc.z), vec3f(1.0 / 2.2)) + dither(in.pos.xy), 1.0);
}
`;

/* ---- hanger (simple lit tube mesh) ---- */
const WGSL_HANGER = WGSL_CAM + WGSL_LIGHT + /* wgsl */`
struct HIn { @location(0) p: vec3f, @location(1) n: vec3f, @location(2) c: vec4f };
struct HOut { @builtin(position) pos: vec4f, @location(0) world: vec3f, @location(1) n: vec3f, @location(2) c: vec4f };
@vertex fn vs(v: HIn) -> HOut {
  var o: HOut; o.pos = cam.viewProj * vec4f(v.p, 1.0); o.world = v.p; o.n = v.n; o.c = v.c;
  return o;
}
@fragment fn fs(in: HOut) -> @location(0) vec4f {
  let N = normalize(in.n); let V = normalize(cam.eye.xyz - in.world);
  let metal = in.c.a;
  let grain = 0.92 + 0.08 * sin(in.world.x * 420.0 + sin(in.world.y * 90.0) * 3.0);
  let alb = in.c.rgb * mix(grain, 1.0, metal);
  let sh = shadowAt(in.world, N, 1.0, 4);
  var col = studio(N, V, alb * (1.0 - metal * 0.7), mix(0.42, 0.22, metal), mix(0.04, 0.75, metal), vec3f(0.0), sh, 1.0);
  let R = reflect(-V, N);
  col += metal * alb * mix(vec3f(0.35), vec3f(1.1), smoothstep(-0.2, 0.8, R.y));   // studio reflection
  return vec4f(pow(aces(col * cam.misc.z), vec3f(1.0 / 2.2)), 1.0);
}
`;

/* ---- pin markers: little enamel pin heads on pinned points ---- */
const WGSL_PINS = WGSL_CAM + /* wgsl */`
@group(0) @binding(1) var<storage, read> rnd: array<vec4f>;
@group(0) @binding(2) var<storage, read> pins: array<u32>;
struct POut { @builtin(position) pos: vec4f, @location(0) q: vec2f };
@vertex fn vs(@builtin(vertex_index) vi: u32, @builtin(instance_index) ii: u32) -> POut {
  var corners = array<vec2f, 6>(vec2f(-1, -1), vec2f(1, -1), vec2f(1, 1), vec2f(-1, -1), vec2f(1, 1), vec2f(-1, 1));
  let k = pins[ii];
  let c = rnd[2u * k].xyz + rnd[2u * k + 1u].xyz * 0.008;
  var clip = cam.viewProj * vec4f(c, 1.0);
  let q = corners[vi];
  clip = vec4f(clip.xy + q * vec2f(cam.res.y * cam.res.z, 1.0) * 0.011 * 2.2, clip.z - 0.002 * clip.w, clip.w);
  var o: POut; o.pos = clip; o.q = q;
  return o;
}
@fragment fn fs(in: POut) -> @location(0) vec4f {
  let r = length(in.q);
  if (r > 1.0) { discard; }
  let n = vec3f(in.q, sqrt(1.0 - r * r));
  let l = max(dot(n, normalize(vec3f(-0.4, 0.6, 0.7))), 0.0);
  let spec = pow(max(dot(reflect(-normalize(vec3f(-0.4, 0.6, 0.7)), n), vec3f(0, 0, 1)), 0.0), 40.0);
  var c = vec3f(0.85, 0.12, 0.14) * (0.25 + 0.85 * l) + spec * 0.8;
  c = mix(c, vec3f(0.98), smoothstep(0.82, 0.9, r));
  return vec4f(pow(c, vec3f(1.0 / 2.2)), 1.0);
}
`;

/* =====================================================================
   CONFIGURATION & STATE
   ===================================================================== */
const IS_MOBILE = matchMedia('(pointer: coarse)').matches || Math.min(screen.width, screen.height) < 700;
const CFG = {
  substeps: 6,                     // sim substeps per 1/60 s (adapted at runtime, see QUALITY)
  iterations: 5,                   // Jacobi iterations per substep (collisions fused in)
  selfPasses: 2,                   // self-collision rounds per 1/60 s
  shadowSize: IS_MOBILE ? 1024 : 2048,
  aoSize: 256,
  maxDpr: 2,
  msaa: 4,
  hashSize: 1 << 15,
  maxPins: 256,
};
const COLOURWAYS = {
  black:    { name: 'Washed Black', base: [0.016, 0.016, 0.0175], wash: 0.7, fuzz: [0.075, 0.075, 0.08], thread: 0.008, exposure: 1.0 },
  bone:     { name: 'Bone White', base: [0.72, 0.66, 0.55], wash: 0.12, fuzz: [0.20, 0.19, 0.17], thread: 0.0, exposure: 0.78 },
  olive:    { name: 'Olive', base: [0.092, 0.098, 0.047], wash: 0.4, fuzz: [0.16, 0.17, 0.11], thread: 0.01, exposure: 1.0 },
  jet:      { name: 'Jet Black', base: [0.011, 0.011, 0.012], wash: 0.16, fuzz: [0.06, 0.06, 0.065], thread: 0.006, exposure: 1.0 },
  burgundy: { name: 'Burgundy', base: [0.15, 0.027, 0.036], wash: 0.4, fuzz: [0.21, 0.10, 0.11], thread: 0.01, exposure: 1.0 },
};
const MODE_LABEL = { hanger: 'Hanger', mannequin: 'Mannequin', free: 'Free Fall' };

const state = {
  mode: 'hanger', paused: false, wind: false, colour: 'black',
  weight: 240, stiffness: 55, stretch: 25, damping: 30, windStrength: 55,
  manqGrow: 1, time: 0, shakeAmp: 0, shakePhase: 0, shakeDir: [1, 0, 0],
  grab: null, userPinPos: new Map(), modePinPos: new Map(),
  frontAspect: 0.2, backAspect: 1.36,
  frontRect: null, backRect: null, autoSpin: 0, userActive: false,
};

let device, context, canvasFormat, G, gpu = {};
let cpuRender = null;                // latest cloth positions/normals read back for picking
let readbackBusy = false;
let cur = 0;                         // which position buffer currently holds the solution

/* =====================================================================
   WEBGPU INITIALISATION
   ===================================================================== */
async function initGPU() {
  if (!navigator.gpu) throw new Error('This browser does not expose navigator.gpu.');
  const adapter = await navigator.gpu.requestAdapter({ powerPreference: 'high-performance' });
  if (!adapter) throw new Error('No compatible GPU adapter was found.');
  device = await adapter.requestDevice();
  device.lost.then((info) => { if (info.reason !== 'destroyed') onDeviceLost(info); });
  device.addEventListener('uncapturederror', (e) => console.error('[WebGPU]', e.error.message));
  context = canvas.getContext('webgpu');
  canvasFormat = navigator.gpu.getPreferredCanvasFormat();
  context.configure({ device, format: canvasFormat, alphaMode: 'opaque' });
}

function makeBuffer(data, usage, size) {
  const buf = device.createBuffer({ size: Math.max(16, Math.ceil((size ?? data.byteLength) / 4) * 4), usage: usage | GPUBufferUsage.COPY_DST });
  if (data) device.queue.writeBuffer(buf, 0, data);
  return buf;
}

/** Creates every GPU buffer the cloth needs. */
function createSimBuffers() {
  const N = G.N, S = GPUBufferUsage.STORAGE, C = GPUBufferUsage.COPY_SRC;
  const stat = new Float32Array(N * 8);
  for (let v = 0; v < N; v++) { stat.set(G.phys.subarray(v * 4, v * 4 + 4), v * 8); stat.set(G.meta.subarray(v * 4, v * 4 + 4), v * 8 + 4); }
  const attr = G.attr;
  gpu.pos = [makeBuffer(null, S | C, N * 16), makeBuffer(null, S | C, N * 16)];
  gpu.prev = makeBuffer(null, S, N * 16);
  gpu.stat = makeBuffer(stat, S);
  gpu.ctrlData = new Float32Array(N * 8);
  gpu.ctrl = makeBuffer(gpu.ctrlData, S);
  gpu.adjRange = makeBuffer(G.adjRange, S);
  gpu.adj = makeBuffer(new Uint8Array(G.adjBuf), S);
  gpu.nbr = makeBuffer(G.nbr, S);
  gpu.partner = makeBuffer(G.partner, S);
  gpu.rnd = makeBuffer(null, S | C, N * 32);
  gpu.attr = makeBuffer(attr, S);
  gpu.hashCount = makeBuffer(null, S, CFG.hashSize * 4);
  gpu.hashCells = makeBuffer(null, S, CFG.hashSize * HASH_SLOTS * 4);
  gpu.index = makeBuffer(G.indices, GPUBufferUsage.INDEX);
  gpu.simUBO = makeBuffer(null, GPUBufferUsage.UNIFORM, 176);
  gpu.camUBO = makeBuffer(null, GPUBufferUsage.UNIFORM, 448);
  gpu.keyUBO = makeBuffer(null, GPUBufferUsage.UNIFORM, 64);
  gpu.aoUBO = makeBuffer(null, GPUBufferUsage.UNIFORM, 64);
  gpu.pinList = makeBuffer(null, S, CFG.maxPins * 4);
  gpu.staging = device.createBuffer({ size: N * 32, usage: GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST });
  cpuRender = new Float32Array(N * 8);
}

function computePipe(code, label) {
  const module = device.createShaderModule({ code, label });
  return device.createComputePipeline({ layout: 'auto', compute: { module, entryPoint: 'main' }, label });
}
function bindGroup(pipe, entries) {
  return device.createBindGroup({
    layout: pipe.getBindGroupLayout(0),
    entries: entries.map((r, i) => ({ binding: r.binding ?? i, resource: r.res ?? { buffer: r } })),
  });
}

/** Builds compute pipelines and the two ping-pong sets of bind groups. */
function createSimPipelines() {
  const P = gpu.pipes = {
    integrate: computePipe(WGSL_INTEGRATE, 'integrate'), solve: computePipe(WGSL_SOLVE, 'solve'),
    clear: computePipe(WGSL_HASH_CLEAR, 'hash-clear'),
    insert: computePipe(WGSL_HASH_INSERT, 'hash-insert'), self: computePipe(WGSL_SELF, 'self-collide'),
    normals: computePipe(WGSL_NORMALS, 'normals'),
  };
  const u = gpu.simUBO, A = gpu.pos;
  gpu.bg = { integrate: [], solve: [], insert: [], self: [], normals: [] };
  for (let c = 0; c < 2; c++) {
    gpu.bg.integrate[c] = bindGroup(P.integrate, [u, A[c], gpu.prev, gpu.stat, gpu.ctrl, gpu.rnd]);
    gpu.bg.solve[c] = bindGroup(P.solve, [u, A[c], A[1 - c], gpu.adjRange, gpu.adj, gpu.ctrl, gpu.prev]);
    gpu.bg.insert[c] = bindGroup(P.insert, [u, A[c], gpu.hashCount, gpu.hashCells]);
    gpu.bg.self[c] = bindGroup(P.self, [u, A[c], A[1 - c], gpu.stat, gpu.hashCount, gpu.hashCells]);
    gpu.bg.normals[c] = bindGroup(P.normals, [u, A[c], gpu.stat, gpu.nbr, gpu.partner, gpu.rnd]);
  }
  gpu.bg.clear = bindGroup(P.clear, [u, gpu.hashCount]);
}

/* =====================================================================
   ARTWORK TEXTURES
   ===================================================================== */
function loadImage(src) {
  return new Promise((res, rej) => { const img = new Image(); img.crossOrigin = 'anonymous'; img.onload = () => res(img); img.onerror = rej; img.src = src; });
}
/** Procedural stand-ins used when a placeholder is left empty or fails to decode. */
function fallbackArt(which) {
  const cv = document.createElement('canvas'), x = cv.getContext('2d');
  if (which === 'front') {
    cv.width = 760; cv.height = 150;
    x.fillStyle = '#fff'; x.textBaseline = 'middle'; x.textAlign = 'center';
    x.font = '500 120px "Century Gothic", Futura, "Avenir Next", Montserrat, "Helvetica Neue", Arial, sans-serif';
    if ('letterSpacing' in x) x.letterSpacing = '14px';
    x.fillText('FORAULS', 380, 80);
  } else {
    cv.width = 720; cv.height = 980;
    x.strokeStyle = '#f0e9dc'; x.fillStyle = '#f0e9dc'; x.lineWidth = 10;
    x.beginPath(); x.arc(360, 420, 260, 0, Math.PI * 2); x.stroke();
    x.textAlign = 'center'; x.font = '600 64px "Century Gothic", Arial, sans-serif'; x.fillText('BACK PRINT', 360, 410);
    x.font = '400 30px Arial, sans-serif'; x.fillText('drop your PNG here', 360, 470);
  }
  return cv;
}
/** Uploads an image as an sRGB texture with a full, canvas-filtered mip chain. */
function makeTexture(img) {
  const maxDim = Math.min(device.limits.maxTextureDimension2D, 2048);
  let w = img.naturalWidth || img.width, h = img.naturalHeight || img.height;
  const s = Math.min(1, maxDim / Math.max(w, h)); w = Math.max(1, Math.round(w * s)); h = Math.max(1, Math.round(h * s));
  const levels = Math.floor(Math.log2(Math.max(w, h))) + 1;
  const tex = device.createTexture({ size: [w, h], format: 'rgba8unorm-srgb', mipLevelCount: levels,
    usage: GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST | GPUTextureUsage.RENDER_ATTACHMENT });
  const cv = document.createElement('canvas'), cx = cv.getContext('2d');
  for (let l = 0, cw = w, ch = h; l < levels; l++, cw = Math.max(1, cw >> 1), ch = Math.max(1, ch >> 1)) {
    cv.width = cw; cv.height = ch; cx.clearRect(0, 0, cw, ch);
    cx.imageSmoothingEnabled = true; cx.imageSmoothingQuality = 'high';
    cx.drawImage(img, 0, 0, cw, ch);
    device.queue.copyExternalImageToTexture({ source: cv }, { texture: tex, mipLevel: l, premultipliedAlpha: false }, [cw, ch]);
  }
  return { tex, aspect: h / w };
}
async function setArtwork(which, src) {
  let img;
  try { img = src ? await loadImage(src) : fallbackArt(which); }
  catch { img = fallbackArt(which); toast('Could not read that image, using a placeholder'); }
  const { tex, aspect } = makeTexture(img);
  const key = which === 'front' ? 'frontTex' : 'backTex';
  if (gpu[key]) { const old = gpu[key]; setTimeout(() => old.destroy(), 500); }
  gpu[key] = tex;
  state[which === 'front' ? 'frontAspect' : 'backAspect'] = aspect;
  if (gpu.pipes?.shirt) buildShirtBindGroup();
}
/** Print placement on the pattern (metres). The back print fills most of the back panel. */
function printRects() {
  const fw = 0.105, fh = fw * state.frontAspect;
  let bw = 0.46, bh = bw * state.backAspect;
  if (bh > 0.6) { bh = 0.6; bw = bh / state.backAspect; }
  return { front: state.frontRect || [0.135, 0.545, fw, fh], back: state.backRect || [0.0, 0.675 - bh / 2, bw, bh] };
}

/**
 * Bakes a tileable 256² "fabric detail" texture once at start-up:
 *   R wash (fbm), G streaks (fbm), B slub (fine noise), A ink-crack cells (voronoi edge distance).
 * Sampling it is far cheaper than evaluating the noise per pixel.
 */
function makeDetailTexture() {
  const S = 256, data = new Uint8Array(S * S * 4);
  const h = (x, y, f, s) => { x = ((x % f) + f) % f; y = ((y % f) + f) % f; let n = (x * 374761393 + y * 668265263 + s * 1442695041) | 0; n = Math.imul(n ^ (n >>> 13), 1274126177); return ((n ^ (n >>> 16)) >>> 0) / 4294967295; };
  const vn = (u, v, f, s) => {
    const x = u * f, y = v * f, xi = Math.floor(x), yi = Math.floor(y), fx = x - xi, fy = y - yi;
    const sx = fx * fx * (3 - 2 * fx), sy = fy * fy * (3 - 2 * fy);
    const a = h(xi, yi, f, s), b = h(xi + 1, yi, f, s), c = h(xi, yi + 1, f, s), d = h(xi + 1, yi + 1, f, s);
    return a + (b - a) * sx + (c - a) * sy + (a - b - c + d) * sx * sy;
  };
  const fbm = (u, v, f, oct, s) => { let t = 0, a = 0.5, n = 0; for (let o = 0; o < oct; o++) { t += a * vn(u, v, f << o, s + o); n += a; a *= 0.5; } return t / n; };
  const C = 24, pts = [];
  for (let j = 0; j < C; j++) for (let i = 0; i < C; i++) pts.push([(i + 0.15 + 0.7 * h(i, j, C, 91)) / C, (j + 0.15 + 0.7 * h(i, j, C, 57)) / C]);
  for (let y = 0; y < S; y++) for (let x = 0; x < S; x++) {
    const u = x / S, v = y / S, o = (y * S + x) * 4;
    data[o] = fbm(u, v, 4, 4, 1) * 255;
    data[o + 1] = fbm(u, v, 8, 3, 7) * 255;
    data[o + 2] = vn(u, v, 32, 13) * 255;
    const ci = Math.floor(u * C), cj = Math.floor(v * C); let d1 = 9, d2 = 9;
    for (let dj = -1; dj <= 1; dj++) for (let di = -1; di <= 1; di++) {
      const ii = ci + di, jj = cj + dj, p = pts[((jj + C) % C) * C + ((ii + C) % C)];
      const px = p[0] + (ii < 0 ? -1 : ii >= C ? 1 : 0), py = p[1] + (jj < 0 ? -1 : jj >= C ? 1 : 0); // wrap across tile edge
      const d = Math.hypot((px - u) * C, (py - v) * C);
      if (d < d1) { d2 = d1; d1 = d; } else if (d < d2) d2 = d;
    }
    data[o + 3] = Math.min(255, (d2 - d1) * 255);
  }
  const levels = Math.log2(S) + 1;
  const tex = device.createTexture({ size: [S, S], format: 'rgba8unorm', mipLevelCount: levels, usage: GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST });
  let src = data, w = S;
  for (let l = 0; l < levels; l++) {
    device.queue.writeTexture({ texture: tex, mipLevel: l }, src, { bytesPerRow: w * 4 }, [w, w]);
    if (w === 1) break;
    const nw = w >> 1, dst = new Uint8Array(nw * nw * 4);
    for (let y = 0; y < nw; y++) for (let x = 0; x < nw; x++) for (let c = 0; c < 4; c++) {
      const i = (k, m) => src[((y * 2 + m) * w + (x * 2 + k)) * 4 + c];
      dst[(y * nw + x) * 4 + c] = (i(0, 0) + i(1, 0) + i(0, 1) + i(1, 1)) >> 2;
    }
    src = dst; w = nw;
  }
  gpu.detailTex = tex;
  gpu.repSamp = device.createSampler({ magFilter: 'linear', minFilter: 'linear', mipmapFilter: 'linear', addressModeU: 'repeat', addressModeV: 'repeat', maxAnisotropy: 4 });
}

/* =====================================================================
   HANGER MESH (wooden bar + chrome hook)
   ===================================================================== */
function tubeMesh(paths) {
  const verts = [], idx = [];
  for (const { pts, r, col, metal } of paths) {
    const seg = 12, base = verts.length / 10;
    let prevN = null;
    for (let i = 0; i < pts.length; i++) {
      const t = v3.norm(v3.sub(pts[Math.min(i + 1, pts.length - 1)], pts[Math.max(i - 1, 0)]));
      let n = prevN ? v3.norm(v3.sub(prevN, v3.scale(t, v3.dot(prevN, t)))) : v3.norm(v3.cross(t, Math.abs(t[2]) < 0.9 ? [0, 0, 1] : [1, 0, 0]));
      prevN = n;
      const b = v3.cross(t, n);
      const rr = typeof r === 'function' ? r(i / (pts.length - 1)) : r;
      for (let k = 0; k <= seg; k++) {
        const a = k / seg * Math.PI * 2, nn = v3.add(v3.scale(n, Math.cos(a)), v3.scale(b, Math.sin(a)));
        const p = v3.add(pts[i], v3.scale(nn, rr));
        verts.push(...p, ...nn, ...col, metal);
      }
    }
    for (let i = 0; i < pts.length - 1; i++) for (let k = 0; k < seg; k++) {
      const a = base + i * (seg + 1) + k, c = a + seg + 1;
      idx.push(a, c, a + 1, a + 1, c, c + 1);
    }
  }
  return { verts: new Float32Array(verts), idx: new Uint32Array(idx) };
}
function buildHanger() {
  const arm = [], hook = [];
  const L = [-0.232, 0.968, 0], C = [0, 1.006, 0], R = [0.232, 0.968, 0];
  for (let i = 0; i <= 40; i++) {
    const t = i / 40, p = t < 0.5 ? v3.lerp(L, C, t * 2) : v3.lerp(C, R, t * 2 - 1);
    p[1] += 0.006 * Math.sin(t * Math.PI);                 // gentle arch
    arm.push(p);
  }
  for (let i = 0; i <= 8; i++) hook.push([0, 1.006 + 0.064 * i / 8, 0]);
  for (let i = 1; i <= 26; i++) { const a = Math.PI - i / 26 * Math.PI * 1.25; hook.push([0.024 + 0.024 * Math.cos(a), 1.07 + 0.024 * Math.sin(a), 0]); }
  const cap = (t) => 0.0115 * Math.sqrt(Math.max(0, 1 - Math.pow(Math.max(0, Math.abs(t - 0.5) * 2 - 0.94) / 0.06, 2)));
  const m = tubeMesh([
    { pts: arm, r: cap, col: [0.42, 0.26, 0.13], metal: 0 },
    { pts: hook, r: 0.0032, col: [0.9, 0.9, 0.92], metal: 1 },
  ]);
  gpu.hangerVB = makeBuffer(m.verts, GPUBufferUsage.VERTEX);
  gpu.hangerIB = makeBuffer(m.idx, GPUBufferUsage.INDEX);
  gpu.hangerCount = m.idx.length;
}

/* =====================================================================
   RENDER PIPELINES & TARGETS
   ===================================================================== */
function renderPipe(code, opts) {
  const module = device.createShaderModule({ code, label: opts.label });
  return device.createRenderPipeline({
    label: opts.label, layout: 'auto',
    vertex: { module, entryPoint: 'vs', buffers: opts.buffers || [] },
    fragment: opts.depthOnly ? undefined : { module, entryPoint: 'fs', targets: [{ format: canvasFormat }] },
    primitive: { topology: 'triangle-list', cullMode: opts.cull || 'none' },
    depthStencil: { format: 'depth32float', depthWriteEnabled: opts.depthWrite ?? true, depthCompare: opts.depthCompare || 'less' },
    multisample: { count: opts.depthOnly ? 1 : CFG.msaa },
  });
}
function createRenderPipelines() {
  const P = gpu.pipes;
  P.bgPipe = renderPipe(WGSL_BG, { label: 'backdrop', depthWrite: false, depthCompare: 'always' });
  P.shirt = renderPipe(WGSL_SHIRT, { label: 'shirt' });
  P.depth = renderPipe(WGSL_DEPTH, { label: 'depth', depthOnly: true });
  P.hanger = renderPipe(WGSL_HANGER, { label: 'hanger', cull: 'back', buffers: [{ arrayStride: 40, attributes: [
    { shaderLocation: 0, offset: 0, format: 'float32x3' }, { shaderLocation: 1, offset: 12, format: 'float32x3' },
    { shaderLocation: 2, offset: 24, format: 'float32x4' }] }] });
  P.pins = renderPipe(WGSL_PINS, { label: 'pins' });

  gpu.shadowTex = device.createTexture({ size: [CFG.shadowSize, CFG.shadowSize], format: 'depth32float', usage: GPUTextureUsage.RENDER_ATTACHMENT | GPUTextureUsage.TEXTURE_BINDING });
  gpu.aoTex = device.createTexture({ size: [CFG.aoSize, CFG.aoSize], format: 'depth32float', usage: GPUTextureUsage.RENDER_ATTACHMENT | GPUTextureUsage.TEXTURE_BINDING });
  makeDetailTexture();
  gpu.linSamp = device.createSampler({ magFilter: 'linear', minFilter: 'linear', mipmapFilter: 'linear', addressModeU: 'clamp-to-edge', addressModeV: 'clamp-to-edge', maxAnisotropy: 8 });
  gpu.cmpSamp = device.createSampler({ compare: 'less', magFilter: 'linear', minFilter: 'linear' });

  const sv = gpu.shadowTex.createView(), cu = gpu.camUBO;
  gpu.bg.bgPipe = bindGroup(P.bgPipe, [cu, { binding: 1, res: gpu.aoTex.createView() }, { binding: 6, res: sv }, { binding: 7, res: gpu.cmpSamp }]);
  gpu.bg.key = bindGroup(P.depth, [gpu.keyUBO, gpu.rnd]);
  gpu.bg.ao = bindGroup(P.depth, [gpu.aoUBO, gpu.rnd]);
  gpu.bg.hanger = bindGroup(P.hanger, [cu, { binding: 6, res: sv }, { binding: 7, res: gpu.cmpSamp }]);
  gpu.bg.pins = bindGroup(P.pins, [cu, gpu.rnd, gpu.pinList]);
  buildShirtBindGroup();
}
function buildShirtBindGroup() {
  if (!gpu.frontTex || !gpu.backTex || !gpu.shadowTex || !gpu.detailTex) return;
  gpu.bg.shirt = bindGroup(gpu.pipes.shirt, [gpu.camUBO, gpu.rnd, gpu.attr,
    { binding: 3, res: gpu.frontTex.createView() }, { binding: 4, res: gpu.backTex.createView() },
    { binding: 5, res: gpu.linSamp }, { binding: 6, res: gpu.shadowTex.createView() }, { binding: 7, res: gpu.cmpSamp },
    { binding: 8, res: gpu.detailTex.createView() }, { binding: 9, res: gpu.repSamp }]);
}

/** (Re)creates the MSAA colour and depth targets when the canvas size changes. */
let renderScale = 1;   // adaptive resolution (see QUALITY)
/**
 * Adaptive quality ladder. If the GPU can't hold ~60 FPS the app steps down:
 * first fewer substeps/iterations, then a lower render resolution; it steps
 * back up when there is headroom.
 */
const QUALITY = [
  { substeps: 6, iterations: 5, scale: 1.0 },
  { substeps: 5, iterations: 5, scale: 1.0 },
  { substeps: 5, iterations: 4, scale: 0.85 },
  { substeps: 4, iterations: 4, scale: 0.72 },
  { substeps: 4, iterations: 4, scale: 0.6 },
];
let qualityLevel = 0;
function applyQuality(level) {
  qualityLevel = clamp(level, 0, QUALITY.length - 1);
  const q = QUALITY[qualityLevel];
  CFG.substeps = q.substeps; CFG.iterations = q.iterations; renderScale = q.scale;
}
function resizeTargets() {
  const dpr = captureReq ? captureReq.dpr : Math.max(0.6, Math.min(window.devicePixelRatio || 1, CFG.maxDpr) * renderScale);
  const w = Math.max(1, Math.floor(canvas.clientWidth * dpr)), h = Math.max(1, Math.floor(canvas.clientHeight * dpr));
  if (canvas.width === w && canvas.height === h && gpu.msaaTex) return;
  canvas.width = w; canvas.height = h;
  gpu.msaaTex?.destroy(); gpu.depthTex?.destroy();
  gpu.msaaTex = device.createTexture({ size: [w, h], format: canvasFormat, sampleCount: CFG.msaa, usage: GPUTextureUsage.RENDER_ATTACHMENT });
  gpu.depthTex = device.createTexture({ size: [w, h], format: 'depth32float', sampleCount: CFG.msaa, usage: GPUTextureUsage.RENDER_ATTACHMENT });
}

/* =====================================================================
   SIMULATION CONTROL (positions, pins, grab)
   ===================================================================== */
function uploadPositions(pos) {
  device.queue.writeBuffer(gpu.pos[0], 0, pos);
  device.queue.writeBuffer(gpu.pos[1], 0, pos);
  device.queue.writeBuffer(gpu.prev, 0, pos);
  cur = 0;
  for (let v = 0; v < G.N; v++) { cpuRender[v * 8] = pos[v * 4]; cpuRender[v * 8 + 1] = pos[v * 4 + 1]; cpuRender[v * 8 + 2] = pos[v * 4 + 2]; }
}
/** Writes pin flags/targets into the control buffer (pins are kinematic particles). */
function uploadPins() {
  const c = gpu.ctrlData;
  for (let v = 0; v < G.N; v++) c[v * 8 + 3] = 0;
  const setPin = (v, p) => { c[v * 8] = p[0]; c[v * 8 + 1] = p[1]; c[v * 8 + 2] = p[2]; c[v * 8 + 3] = 1; };
  for (const [v, p] of state.modePinPos || []) setPin(v, p);
  for (const [v, p] of state.userPinPos) setPin(v, p);
  device.queue.writeBuffer(gpu.ctrl, 0, c);
  const list = new Uint32Array(CFG.maxPins); let n = 0;
  for (const v of state.userPinPos.keys()) if (n < CFG.maxPins) list[n++] = v;
  gpu.pinCount = n;
  device.queue.writeBuffer(gpu.pinList, 0, list);
}
function clearGrabWeights() { const c = gpu.ctrlData; for (let v = 0; v < G.N; v++) c[v * 8 + 7] = 0; }

/* =====================================================================
   PER-FRAME UNIFORMS
   ===================================================================== */
const simData = new Float32Array(44), simU32 = new Uint32Array(simData.buffer);
function writeSimUniforms() {
  const s = state, dt = 1 / 60 / CFG.substeps;
  const str = s.stretch / 100, stf = s.stiffness / 100;
  const aStretch = 5 * str * str;                                      // structural compliance
  const aBend = 400 * Math.pow(2.5 / 400, stf);                        // bending compliance (log scale)
  const windSpeed = s.wind ? 5.2 * s.windStrength / 100 : 0;
  const wd = v3.norm([0.85, 0.08, -0.55]);
  const gust = s.wind ? 0.35 * Math.sin(s.time * 0.61) * Math.sin(s.time * 1.73 + 1.3) + 0.25 * Math.max(0, Math.sin(s.time * 0.29)) : 0;
  const g = s.grab;
  simData.set([dt, s.time, 9.81, 1.9,
    aStretch, aStretch + 0.5, aBend, 0.003 + 1.5 * str * str,
    wd[0] * windSpeed, wd[1] * windSpeed, wd[2] * windSpeed, gust,
    g ? g.target[0] : 0, g ? g.target[1] : 0, g ? g.target[2] : 0, g ? 1 : 0,
    ...(g ? g.q : [0, 0, 0, 1]),
    s.shakeDir[0] * s.shakeAmp, s.shakeDir[1] * s.shakeAmp, s.shakeDir[2] * s.shakeAmp, s.shakePhase,
    s.mode === 'mannequin' ? 1 : 0, s.manqGrow, 0, 0,
    s.mode === 'hanger' ? 1 : 0, 0, 0, 0,
    0, 0.55, 0.006, 0,
    1.35, 0.85, 0.017, 0,
    s.weight / 240, 0.05 + 3 * Math.pow(s.damping / 100, 2), 0.0085, G.spacing * 1.9]);
  simU32[35] = G.N;
  simU32[39] = CFG.hashSize - 1;
  device.queue.writeBuffer(gpu.simUBO, 0, simData);
}

const camData = new Float32Array(112);
function writeCamUniforms(view) {
  const cw = COLOURWAYS[state.colour], r = printRects(), lights = view.lights;
  camData.set(view.viewProj, 0); camData.set(m4.invert(view.viewProj), 16);
  camData.set(view.keyVP, 32); camData.set(view.aoVP, 48);
  camData.set([...view.eye, 1, ...cw.base, cw.wash, ...cw.fuzz, cw.thread, ...r.front, ...r.back,
    state.time, 1 / CFG.shadowSize, cw.exposure, 0,
    canvas.width, canvas.height, 1 / canvas.width, 1 / canvas.height,
    ...lights.key, 0, ...lights.fill, 0, ...lights.rimL, 0, ...lights.rimR, 0,
    view.aoEyeY, view.aoRange, CFG.aoSize, view.aoHalf], 64);
  device.queue.writeBuffer(gpu.camUBO, 0, camData);
  device.queue.writeBuffer(gpu.keyUBO, 0, view.keyVP);
  device.queue.writeBuffer(gpu.aoUBO, 0, view.aoVP);
}

/* =====================================================================
   COMMAND ENCODING
   ===================================================================== */
/** One 1/60 s step: substeps of integrate → Jacobi solve with fused collisions (+ self-collision). */
function encodeSimStep(pass) {
  const wg = Math.ceil(G.N / 64), B = gpu.bg, P = gpu.pipes;
  for (let s = 0; s < CFG.substeps; s++) {
    pass.setPipeline(P.integrate); pass.setBindGroup(0, B.integrate[cur]); pass.dispatchWorkgroups(wg);
    pass.setPipeline(P.solve);
    for (let it = 0; it < CFG.iterations; it++) { pass.setBindGroup(0, B.solve[cur]); pass.dispatchWorkgroups(wg); cur ^= 1; }
    const every = Math.max(1, Math.round(CFG.substeps / CFG.selfPasses));
    if (s % every === every - 1) {
      pass.setPipeline(P.clear); pass.setBindGroup(0, B.clear); pass.dispatchWorkgroups(Math.ceil(CFG.hashSize / 64));
      pass.setPipeline(P.insert); pass.setBindGroup(0, B.insert[cur]); pass.dispatchWorkgroups(wg);
      pass.setPipeline(P.self); pass.setBindGroup(0, B.self[cur]); pass.dispatchWorkgroups(wg); cur ^= 1;
    }
  }
}
function encodeNormals(pass) {
  pass.setPipeline(gpu.pipes.normals); pass.setBindGroup(0, gpu.bg.normals[cur]); pass.dispatchWorkgroups(Math.ceil(G.N / 64));
}
function encodeDepth(enc, tex, bg) {
  const pass = enc.beginRenderPass({ colorAttachments: [], depthStencilAttachment: { view: tex.createView(), depthClearValue: 1, depthLoadOp: 'clear', depthStoreOp: 'store' } });
  pass.setPipeline(gpu.pipes.depth); pass.setBindGroup(0, bg);
  pass.setIndexBuffer(gpu.index, 'uint32'); pass.drawIndexed(G.indices.length);
  pass.end();
}
function encodeMain(enc) {
  const P = gpu.pipes, B = gpu.bg;
  const pass = enc.beginRenderPass({
    colorAttachments: [{ view: gpu.msaaTex.createView(), resolveTarget: context.getCurrentTexture().createView(), loadOp: 'clear', storeOp: 'discard', clearValue: captureReq ? [0, 0, 0, 0] : [0.9, 0.9, 0.91, 1] }],
    depthStencilAttachment: { view: gpu.depthTex.createView(), depthClearValue: 1, depthLoadOp: 'clear', depthStoreOp: 'discard' },
  });
  if (!captureReq) { pass.setPipeline(P.bgPipe); pass.setBindGroup(0, B.bgPipe); pass.draw(3); }
  if (state.mode === 'hanger') {
    pass.setPipeline(P.hanger); pass.setBindGroup(0, B.hanger);
    pass.setVertexBuffer(0, gpu.hangerVB); pass.setIndexBuffer(gpu.hangerIB, 'uint32'); pass.drawIndexed(gpu.hangerCount);
  }
  pass.setPipeline(P.shirt); pass.setBindGroup(0, B.shirt);
  pass.setIndexBuffer(gpu.index, 'uint32'); pass.drawIndexed(G.indices.length);
  if (gpu.pinCount && !captureReq) { pass.setPipeline(P.pins); pass.setBindGroup(0, B.pins); pass.draw(6, gpu.pinCount); }
  pass.end();
}
/** Copies cloth positions back to the CPU (one in flight) for picking and framing. */
let readbackTick = 0;
function encodeReadback(enc) {
  if (readbackBusy || (readbackTick++ & 1)) return false;
  enc.copyBufferToBuffer(gpu.rnd, 0, gpu.staging, 0, G.N * 32);
  return true;
}
function finishReadback() {
  readbackBusy = true;
  gpu.staging.mapAsync(GPUMapMode.READ).then(() => {
    cpuRender.set(new Float32Array(gpu.staging.getMappedRange()));
    gpu.staging.unmap(); readbackBusy = false;
  }).catch(() => { readbackBusy = false; });
}

/* =====================================================================
   CAMERA (orbit / pan / zoom with smooth damping)
   ===================================================================== */
const camera = { yaw: 0, pitch: 0.06, dist: 2.45, target: [0, 0.62, 0], fov: 34 * Math.PI / 180,
  goal: { yaw: 0, pitch: 0.06, dist: 2.45, target: [0, 0.62, 0] } };
let lastView = null;

function updateCamera(dt) {
  const k = 1 - Math.exp(-dt * 8), c = camera, g = c.goal;
  c.yaw += (g.yaw - c.yaw) * k; c.pitch += (g.pitch - c.pitch) * k; c.dist += (g.dist - c.dist) * k;
  c.target = v3.lerp(c.target, g.target, k);
}
function clothCenter() {
  let mn = [1e9, 1e9, 1e9], mx = [-1e9, -1e9, -1e9];
  for (let v = 0; v < G.N; v += 3) for (let a = 0; a < 3; a++) {
    const x = cpuRender[v * 8 + a]; if (x < mn[a]) mn[a] = x; if (x > mx[a]) mx[a] = x;
  }
  return [(mn[0] + mx[0]) / 2, clamp((mn[1] + mx[1]) / 2, 0.2, 1.5), (mn[2] + mx[2]) / 2];
}
function viewInfo() {
  const c = camera, cp = Math.cos(c.pitch);
  const eye = [c.target[0] + c.dist * Math.sin(c.yaw) * cp, c.target[1] + c.dist * Math.sin(c.pitch), c.target[2] + c.dist * Math.cos(c.yaw) * cp];
  const aspect = canvas.width / canvas.height;
  // portrait screens: widen the vertical field of view so the whole shirt stays in frame
  const fov = aspect < 0.9 ? 2 * Math.atan(Math.tan(c.fov / 2) * 0.74 / Math.max(aspect, 0.45)) : c.fov;
  const viewProj = m4.mul(m4.perspective(fov, aspect, 0.03, 60), m4.lookAt(eye, c.target, [0, 1, 0]));
  // the studio rig turns with the camera, like a product on a turntable
  const s = Math.sin(c.yaw), co = Math.cos(c.yaw);
  const rot = (v) => { const n = v3.norm(v); return [n[0] * co + n[2] * s, n[1], -n[0] * s + n[2] * co]; };
  const lights = { key: rot([-0.55, 0.8, 0.62]), fill: rot([0.85, 0.2, 0.6]), rimL: rot([-0.8, 0.42, -0.8]), rimR: rot([0.85, 0.5, -0.75]) };
  const ctr = clothCenter();
  const keyVP = m4.mul(m4.ortho(-1.3, 1.3, -1.3, 1.3, 0.3, 7), m4.lookAt(v3.add(ctr, v3.scale(lights.key, 3.2)), ctr, [0, 1, 0]));
  const aoEyeY = -0.05, aoRange = 2.5, aoHalf = 1.6;
  const aoVP = m4.mul(m4.ortho(-aoHalf, aoHalf, -aoHalf, aoHalf, 0, aoRange), m4.lookAt([0, aoEyeY, 0], [0, 1, 0], [0, 0, 1]));
  return { eye, viewProj, lights, keyVP, aoVP, aoEyeY, aoRange, aoHalf, fov };
}
function setCameraGoal(o) { Object.assign(camera.goal, o); }

/* =====================================================================
   PICKING (CPU ray cast against the read-back cloth)
   ===================================================================== */
function screenRay(x, y) {
  const r = canvas.getBoundingClientRect();
  const nx = (x - r.left) / r.width * 2 - 1, ny = 1 - (y - r.top) / r.height * 2;
  const inv = m4.invert(lastView.viewProj);
  const un = (z) => {
    const v = [0, 0, 0, 0];
    for (let i = 0; i < 4; i++) v[i] = inv[i] * nx + inv[4 + i] * ny + inv[8 + i] * z + inv[12 + i];
    return [v[0] / v[3], v[1] / v[3], v[2] / v[3]];
  };
  const o = un(0), f = un(1);
  return { o, d: v3.norm(v3.sub(f, o)) };
}
function pickCloth(ray) {
  const P = cpuRender, I = G.indices, [ox, oy, oz] = ray.o, [dx, dy, dz] = ray.d;
  let best = Infinity, bt = -1, bu = 0, bv = 0;
  for (let t = 0; t < I.length; t += 3) {
    const a = I[t] * 8, b = I[t + 1] * 8, c = I[t + 2] * 8;
    const e1x = P[b] - P[a], e1y = P[b + 1] - P[a + 1], e1z = P[b + 2] - P[a + 2];
    const e2x = P[c] - P[a], e2y = P[c + 1] - P[a + 1], e2z = P[c + 2] - P[a + 2];
    const px = dy * e2z - dz * e2y, py = dz * e2x - dx * e2z, pz = dx * e2y - dy * e2x;
    const det = e1x * px + e1y * py + e1z * pz;
    if (Math.abs(det) < 1e-12) continue;
    const inv = 1 / det, tx = ox - P[a], ty = oy - P[a + 1], tz = oz - P[a + 2];
    const u = (tx * px + ty * py + tz * pz) * inv; if (u < 0 || u > 1) continue;
    const qx = ty * e1z - tz * e1y, qy = tz * e1x - tx * e1z, qz = tx * e1y - ty * e1x;
    const v = (dx * qx + dy * qy + dz * qz) * inv; if (v < 0 || u + v > 1) continue;
    const d = (e2x * qx + e2y * qy + e2z * qz) * inv;
    if (d > 0 && d < best) { best = d; bt = t; bu = u; bv = v; }
  }
  if (bt < 0) return null;
  const w = [1 - bu - bv, bu, bv], k = w.indexOf(Math.max(...w));
  return { vertex: I[bt + k], point: v3.add(ray.o, v3.scale(ray.d, best)) };
}

/* =====================================================================
   INTERACTION: grab / twist / fling, pins, shake
   ===================================================================== */
function beginGrab(hit) {
  clearGrabWeights();
  const v0 = hit.vertex, panel = G.panelOf[v0], c = gpu.ctrlData, sigma = 0.03;
  for (let v = 0; v < G.N; v++) {
    if (G.panelOf[v] !== panel) continue;
    const d = Math.hypot(G.px[v] - G.px[v0], G.py[v] - G.py[v0]);
    if (d > 0.075) continue;
    c[v * 8 + 4] = cpuRender[v * 8] - hit.point[0];
    c[v * 8 + 5] = cpuRender[v * 8 + 1] - hit.point[1];
    c[v * 8 + 6] = cpuRender[v * 8 + 2] - hit.point[2];
    c[v * 8 + 7] = 0.6 * Math.exp(-d * d / (2 * sigma * sigma));
  }
  device.queue.writeBuffer(gpu.ctrl, 0, c);
  state.grab = { target: hit.point.slice(), anchor: hit.point.slice(), normal: v3.norm(v3.sub(camera.target, lastView.eye)),
    q: [0, 0, 0, 1], twist: 0, last: null, lastDir: null, flips: [] };
  canvas.classList.add('grabbing');
}
function moveGrab(x, y) {
  const g = state.grab, ray = screenRay(x, y), den = v3.dot(ray.d, g.normal);
  if (Math.abs(den) < 1e-4) return;
  const t = v3.dot(v3.sub(g.anchor, ray.o), g.normal) / den;
  const p = v3.add(ray.o, v3.scale(ray.d, t));
  p[1] = Math.max(p[1], 0.02);
  // shake gesture: several fast direction reversals within ~0.7 s
  const now = performance.now();
  if (g.last) {
    const dtm = Math.max(1, now - g.last.t), mv = [x - g.last.x, y - g.last.y], sp = Math.hypot(mv[0], mv[1]) / dtm;
    if (sp > 0.9) {
      const dir = [mv[0] / (sp * dtm), mv[1] / (sp * dtm)];
      if (g.lastDir && dir[0] * g.lastDir[0] + dir[1] * g.lastDir[1] < -0.3) g.flips.push(now);
      g.lastDir = dir;
    }
    g.flips = g.flips.filter((f) => now - f < 700);
    if (g.flips.length >= 3) { triggerShake(v3.sub(p, g.target), 1.0); g.flips = []; }
  }
  g.last = { x, y, t: now };
  g.target = p;
}
function twistGrab(delta) {
  const g = state.grab; g.twist += delta;
  const ax = g.normal, h = g.twist / 2, s = Math.sin(h);
  g.q = [ax[0] * s, ax[1] * s, ax[2] * s, Math.cos(h)];
}
function endGrab() {
  if (!state.grab) return;
  state.grab = null; canvas.classList.remove('grabbing');
}
/** Returns a user pin within ~3.5 cm of a hit point (so pins can be dragged around). */
function pinNear(point) {
  let best = null, bd = 0.035;
  for (const [v, p] of state.userPinPos) { const d = v3.len(v3.sub(p, point)); if (d < bd) { bd = d; best = v; } }
  return best;
}
function dragPin(gst, x, y) {
  const ray = screenRay(x, y), den = v3.dot(ray.d, gst.normal);
  if (Math.abs(den) < 1e-4) return;
  const t = v3.dot(v3.sub(gst.anchor, ray.o), gst.normal) / den;
  const p = v3.add(ray.o, v3.scale(ray.d, t)); p[1] = Math.max(p[1], 0.01);
  state.userPinPos.set(gst.v, p);
  const c = gpu.ctrlData, v = gst.v;
  c[v * 8] = p[0]; c[v * 8 + 1] = p[1]; c[v * 8 + 2] = p[2]; c[v * 8 + 3] = 1;
  device.queue.writeBuffer(gpu.ctrl, v * 32, c, v * 8, 4);
}

let lastShakeToast = 0;
function triggerShake(dir, strength) {
  let d = v3.len(dir) > 1e-5 ? v3.norm(dir) : v3.norm([Math.random() - 0.5, 0.3, Math.random() - 0.5]);
  d = v3.norm(v3.add(d, [0, 0.35, 0]));
  state.shakeDir = d; state.shakeAmp = 34 * strength;
  if (performance.now() - lastShakeToast > 1200) { toast('Shake!'); lastShakeToast = performance.now(); }
}
function togglePinAt(x, y) {
  const hit = pickCloth(screenRay(x, y));
  if (!hit) return;
  const v = hit.vertex;
  if (state.userPinPos.has(v)) { state.userPinPos.delete(v); toast('Unpinned'); }
  else {
    // double-clicking near the hanger releases that whole shoulder
    let near = false;
    for (const [m, p] of state.modePinPos) if (v3.len(v3.sub(p, hit.point)) < 0.05) { near = true; break; }
    if (near) {
      const side = Math.sign(G.px[v]) || 1;
      for (const m of [...state.modePinPos.keys()]) if (Math.sign(G.px[m]) === side) state.modePinPos.delete(m);
      toast('Released one shoulder from the hanger');
    } else {
      state.userPinPos.set(v, [cpuRender[v * 8], cpuRender[v * 8 + 1], cpuRender[v * 8 + 2]]);
      toast('Pinned · drag the pin to move it, double-click to release');
    }
  }
  uploadPins();
}

/* =====================================================================
   MODES
   ===================================================================== */
function setMode(mode, fromButton = false) {
  const keep = mode === 'free' && fromButton && state.mode !== 'free';
  state.mode = mode; endGrab();
  state.userPinPos.clear(); state.modePinPos.clear();
  if (!keep) {
    const pos = layoutShirt(G, mode);
    uploadPositions(pos);
    if (mode === 'hanger') for (const v of G.hangerPins) state.modePinPos.set(v, [pos[v * 4], pos[v * 4 + 1], pos[v * 4 + 2]]);
  }
  state.manqGrow = mode === 'mannequin' ? 0 : 1;
  uploadPins();
  gpu.needNormals = true;
  if (mode === 'free') setCameraGoal({ target: [0, 0.32, 0], pitch: 0.42, dist: 2.3 });
  else setCameraGoal({ target: [0, 0.62, 0], pitch: 0.06, dist: 2.45 });
  opts.onMode?.(mode);
}

/* ---- pointer: mouse + touch (grab, orbit, pan, pinch, double-tap) ---- */
function wirePointer() {
  const pointers = new Map();
  let gesture = null, lastTap = { t: 0, x: 0, y: 0 }, downInfo = null, hoverT = 0;
  const panBy = (dx, dy) => {
    const c = camera, scale = 2 * c.dist * Math.tan(lastView.fov / 2) / canvas.clientHeight;
    const right = [Math.cos(c.yaw), 0, -Math.sin(c.yaw)];
    const up = [-Math.sin(c.pitch) * Math.sin(c.yaw), Math.cos(c.pitch), -Math.sin(c.pitch) * Math.cos(c.yaw)];
    const t = camera.goal.target;
    camera.goal.target = [t[0] - right[0] * dx * scale + up[0] * dy * scale, clamp(t[1] - right[1] * dx * scale + up[1] * dy * scale, -0.5, 2.5), t[2] - right[2] * dx * scale + up[2] * dy * scale];
  };
  const pinchInfo = () => {
    const [a, b] = [...pointers.values()];
    return { d: Math.hypot(a.x - b.x, a.y - b.y), mx: (a.x + b.x) / 2, my: (a.y + b.y) / 2 };
  };

  listen(canvas, 'contextmenu', (e) => e.preventDefault());
  listen(canvas, 'pointerdown', (e) => {
    canvas.focus({ preventScroll: true });
    canvas.setPointerCapture(e.pointerId);
    pointers.set(e.pointerId, { x: e.clientX, y: e.clientY });
    state.userActive = true; opts.onInteract?.();
    downInfo = { t: performance.now(), x: e.clientX, y: e.clientY };
    if (pointers.size === 2) {
      endGrab();
      const p = pinchInfo(); gesture = { type: 'pinch', d0: p.d, dist0: camera.goal.dist, mx: p.mx, my: p.my };
      return;
    }
    if (pointers.size > 2) return;
    const pan = e.button === 1 || e.button === 2 || e.shiftKey;
    if (!pan && e.button === 0) {
      const hit = pickCloth(screenRay(e.clientX, e.clientY));
      if (hit) {
        const pv = pinNear(hit.point);
        if (pv !== null) {      // dragging an existing pin moves it (hang the shirt like a clothesline)
          gesture = { type: 'pin', v: pv, anchor: state.userPinPos.get(pv).slice(), normal: v3.norm(v3.sub(camera.target, lastView.eye)) };
          canvas.classList.add('grabbing');
          return;
        }
        beginGrab(hit); gesture = { type: 'grab' }; return;
      }
    }
    gesture = { type: pan ? 'pan' : 'orbit', x: e.clientX, y: e.clientY };
  });
  listen(canvas, 'pointermove', (e) => {
    const pt = pointers.get(e.pointerId);
    if (!pt) {
      // hover feedback (mouse only, throttled)
      if (e.pointerType === 'mouse' && performance.now() - hoverT > 60 && lastView) {
        hoverT = performance.now();
        canvas.classList.toggle('over-cloth', !!pickCloth(screenRay(e.clientX, e.clientY)));
      }
      return;
    }
    const dx = e.clientX - pt.x, dy = e.clientY - pt.y;
    pt.x = e.clientX; pt.y = e.clientY;
    if (!gesture) return;
    if (gesture.type === 'grab' && state.grab) moveGrab(e.clientX, e.clientY);
    else if (gesture.type === 'pin') dragPin(gesture, e.clientX, e.clientY);
    else if (gesture.type === 'orbit') {
      camera.goal.yaw -= dx * 0.0085;
      camera.goal.pitch = clamp(camera.goal.pitch + dy * 0.006, -0.3, 1.35);
      updateFlipLabel();
    } else if (gesture.type === 'pan') panBy(dx, dy);
    else if (gesture.type === 'pinch' && pointers.size === 2) {
      const p = pinchInfo();
      camera.goal.dist = clamp(gesture.dist0 * gesture.d0 / Math.max(p.d, 1), 0.6, 6);
      panBy(p.mx - gesture.mx, p.my - gesture.my);
      gesture.mx = p.mx; gesture.my = p.my;
    }
  });
  const up = (e) => {
    if (!pointers.has(e.pointerId)) return;
    pointers.delete(e.pointerId);
    state.userActive = pointers.size > 0;
    if (gesture?.type === 'grab') endGrab();
    if (gesture?.type === 'pin') canvas.classList.remove('grabbing');
    // touch double-tap toggles a pin
    if (e.pointerType !== 'mouse' && downInfo && performance.now() - downInfo.t < 260 && Math.hypot(e.clientX - downInfo.x, e.clientY - downInfo.y) < 12) {
      const now = performance.now();
      if (now - lastTap.t < 340 && Math.hypot(e.clientX - lastTap.x, e.clientY - lastTap.y) < 36) { togglePinAt(e.clientX, e.clientY); lastTap.t = 0; }
      else lastTap = { t: now, x: e.clientX, y: e.clientY };
    }
    gesture = pointers.size === 1 ? { type: 'orbit' } : null;
  };
  listen(canvas, 'pointerup', up);
  listen(canvas, 'pointercancel', up);
  listen(canvas, 'dblclick', (e) => togglePinAt(e.clientX, e.clientY));
  listen(canvas, 'wheel', (e) => {
    if (!state.grab && !(e.ctrlKey || e.metaKey)) return;   // plain wheel scrolls the page
    e.preventDefault();
    const dy = e.deltaMode === 1 ? e.deltaY * 16 : e.deltaY;
    if (state.grab) twistGrab(dy * 0.004);
    else camera.goal.dist = clamp(camera.goal.dist * Math.exp(dy * 0.0011), 0.6, 6);
  }, { passive: false });
}


/* =====================================================================
   MAIN LOOP (adapted: start/stop, auto-spin, yaw reporting)
   ===================================================================== */
let lastT = performance.now(), acc = 0, fpsAvg = 60, scaleT = performance.now() + 2500;
const baseQuality = opts.lite ? QUALITY.length - 2 : IS_MOBILE ? 1 : 0;
let raf = 0, running = false, destroyed = false, booted = false, lostInfo = null, lastYaw = NaN;

/** A lost device can't be revived: stop submitting work and let the host rebuild us. */
function onDeviceLost(info) {
  lostInfo = info; stop();
  if (captureReq) { captureReq.reject(new Error('The GPU device was lost.')); captureReq = null; }
  if (booted && !destroyed) opts.onError?.(new Error('The GPU device was lost (' + info.message + ').'));
}

/* ---- capture: a transparent, high-resolution still of the tee (product images) ---- */
let captureReq = null, restoreOpaque = false;
const CAPTURE_VIEW = { pitch: 0.06, dist: 2.45, target: [0, 0.62, 0] };
/**
 * Renders the tee from `yaw` (0 = front, π = back) on a transparent background
 * at `dpr` × the canvas's CSS size and resolves to a 2D canvas copy of it.
 */
function capture({ yaw = 0, dpr = 2.5 } = {}) {
  if (destroyed || lostInfo) return Promise.reject(new Error('The 3D view is not running.'));
  if (captureReq) return Promise.reject(new Error('A capture is already in progress.'));
  const saved = { ...camera.goal };
  Object.assign(camera.goal, CAPTURE_VIEW, { yaw });
  Object.assign(camera, CAPTURE_VIEW, { yaw, target: [...CAPTURE_VIEW.target] });
  return new Promise((resolve, reject) => {
    const done = (fn) => (v) => {
      clearTimeout(timer);
      if (captureReq === req) captureReq = null;
      restoreOpaque = true;
      Object.assign(camera.goal, saved);
      fn(v);
    };
    const req = { frames: 2, dpr, armed: false, resolve: done(resolve), reject: done(reject) };
    const timer = setTimeout(() => req.reject(new Error('Capturing the 3D view timed out.')), 5000);
    captureReq = req;
    start();
  });
}
function captureFrame() {
  const req = captureReq;
  if (--req.frames > 0) return;
  try {
    const out = document.createElement('canvas');
    out.width = canvas.width; out.height = canvas.height;
    out.getContext('2d').drawImage(canvas, 0, 0);   // same task as the submit: reads this frame
    req.resolve(out);
  } catch (e) { req.reject(e); }
}

function frame(now) {
  if (destroyed || !running) return;
  const dt = Math.min(0.1, (now - lastT) / 1000); lastT = now;
  fpsAvg += ((1 / Math.max(dt, 1e-3)) - fpsAvg) * 0.08;
  if (!document.hidden && now - scaleT > 1500) {
    if (fpsAvg < 50 && qualityLevel < QUALITY.length - 1) { applyQuality(qualityLevel + 1); scaleT = now; }
    else if (fpsAvg > 59 && qualityLevel > baseQuality && now - scaleT > 4000) { applyQuality(qualityLevel - 1); scaleT = now; }
  }
  if (state.autoSpin && !state.userActive && !state.grab && !captureReq) camera.goal.yaw += state.autoSpin * dt;
  if (captureReq && !captureReq.armed) {
    context.configure({ device, format: canvasFormat, alphaMode: 'premultiplied' });
    captureReq.armed = true; scaleT = now;
  } else if (restoreOpaque && !captureReq) {
    context.configure({ device, format: canvasFormat, alphaMode: 'opaque' });
    restoreOpaque = false;
  }

  resizeTargets();
  updateCamera(dt);
  if (!(Math.abs(camera.yaw - lastYaw) < 1e-4)) { lastYaw = camera.yaw; opts.onYaw?.(camera.yaw); }
  let steps = 0;
  if (!state.paused) {
    acc += dt;
    const maxSteps = fpsAvg > 50 ? 2 : 1;
    while (acc >= 1 / 60 && steps < maxSteps) { acc -= 1 / 60; steps++; }
    if (acc > 1 / 30) acc = 0;
    state.shakeAmp *= Math.exp(-dt * 2.2);
    state.shakePhase += dt * 24;
    if (state.manqGrow < 1) state.manqGrow = Math.min(1, state.manqGrow + dt / 1.2);
  }
  lastView = viewInfo();

  const enc = device.createCommandEncoder();
  if (steps > 0 || gpu.needNormals) {
    state.time += steps / 60;
    writeSimUniforms();
    const pass = enc.beginComputePass();
    for (let i = 0; i < steps; i++) encodeSimStep(pass);
    encodeNormals(pass);
    pass.end();
    gpu.needNormals = false;
  }
  writeCamUniforms(lastView);
  encodeDepth(enc, gpu.shadowTex, gpu.bg.key);
  encodeDepth(enc, gpu.aoTex, gpu.bg.ao);
  encodeMain(enc);
  const rb = encodeReadback(enc);
  device.queue.submit([enc.finish()]);
  if (rb) finishReadback();
  if (captureReq) captureFrame();
  raf = requestAnimationFrame(frame);
}
function start() {
  if (running || destroyed) return;
  running = true; lastT = performance.now();
  raf = requestAnimationFrame(frame);
}
function stop() { running = false; cancelAnimationFrame(raf); }

/** Optional framing offset so the tee sits clear of overlaid UI: { dy (m), dist (scale) }. */
function applyFraming() {
  const f = opts.framing; if (!f) return;
  const t = camera.goal.target;
  camera.goal.target = [t[0], t[1] + (f.dy || 0), t[2]];
  camera.goal.dist *= f.dist || 1;
}

/** Loads front/back artwork; a rect places it on the pattern (metres: cx, cy, w, h). No print = plain fabric. */
async function applyPrint(which, p) {
  if (p?.src) await setArtwork(which, p.src);
  else clearArtwork(which);
  state[which === 'front' ? 'frontRect' : 'backRect'] = p?.rect ?? null;
}
function clearArtwork(which) {
  const blank = document.createElement('canvas'); blank.width = blank.height = 4;   // fully transparent
  const key = which === 'front' ? 'frontTex' : 'backTex';
  if (gpu[key]) { const old = gpu[key]; setTimeout(() => old.destroy(), 500); }
  gpu[key] = makeTexture(blank).tex;
  if (gpu.pipes?.shirt) buildShirtBindGroup();
}

/* =====================================================================
   BOOT
   ===================================================================== */
await initGPU();
if (opts.lite) CFG.shadowSize = 1024;
device.pushErrorScope('validation');
G = buildGarment();
createSimBuffers();
createSimPipelines();
buildHanger();
await Promise.all([applyPrint('front', opts.front), applyPrint('back', opts.back)]);
createRenderPipelines();
const bootErr = await device.popErrorScope();
if (bootErr || lostInfo) {
  device.destroy();
  throw new Error(bootErr ? bootErr.message : 'The GPU device was lost during start-up (' + lostInfo.message + ').');
}
applyQuality(baseQuality);
wirePointer();
if (opts.colour && COLOURWAYS[opts.colour]) state.colour = opts.colour;
state.autoSpin = opts.autoSpin || 0;
setMode(opts.mode || 'mannequin');
applyFraming();
camera.yaw = camera.goal.yaw = opts.yaw || 0;
lastView = viewInfo();
booted = true;
start();

return {
  /** Swap artwork: { front: { src, rect }, back: { src, rect } } */
  setPrints: (p) => Promise.all([applyPrint('front', p.front), applyPrint('back', p.back)]),
  /** Move/resize one print without reloading it: rect = [cx, cy, w, h] in pattern metres (null = default). */
  setPrintRect: (which, rect) => { state[which === 'front' ? 'frontRect' : 'backRect'] = rect ?? null; },
  /** Transparent still of the tee: { yaw, dpr } → Promise<HTMLCanvasElement>. */
  capture,
  setColour: (id) => { if (COLOURWAYS[id]) state.colour = id; },
  setMode: (m) => { setMode(m, true); applyFraming(); },
  reset: () => { setMode(state.mode); applyFraming(); },
  setWind: (on) => { state.wind = !!on; },
  shake: () => triggerShake([0, 0, 0], 1),
  setAutoSpin: (radPerSec) => { state.autoSpin = radPerSec || 0; },
  /** Orbit the camera to `rad` (smoothed); immediate skips the easing. */
  setYaw: (rad, immediate = false) => { camera.goal.yaw = rad; if (immediate) camera.yaw = rad; },
  getYaw: () => camera.goal.yaw,
  zoom: (factor) => { camera.goal.dist = clamp(camera.goal.dist * factor, 0.6, 6); },
  setActive: (on) => (on ? start() : stop()),
  destroy: () => {
    destroyed = true; stop();
    captureReq?.reject(new Error('The 3D view was closed.'));
    cleanups.forEach((f) => f());
    try { device.destroy(); } catch (e) { /* already gone */ }
  },
};
}
