/**
 * Writes supabase/seed.sql: the bundled catalog (src/data/products.js) as rows
 * for the Supabase `products` table. Existing rows are left alone, so it's safe
 * to run again after adding products in the admin.
 *
 * Usage: node scripts/make-seed.mjs
 */
import { writeFile } from 'node:fs/promises';
import { createServer } from 'vite';

const vite = await createServer({ server: { middlewareMode: true, hmr: false }, appType: 'custom', logLevel: 'error' });
const { products } = await vite.ssrLoadModule('/src/data/products.js');
const { toRow } = await vite.ssrLoadModule('/src/data/catalog.js');
await vite.close();

const lit = (v) => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const rows = products.map(toRow);
const cols = Object.keys(rows[0]);
const sql = `-- GENERATED by scripts/make-seed.mjs — the built-in catalog as Supabase rows.
-- Run after schema.sql (SQL Editor → New query → paste → Run). Rows that already exist are skipped.
insert into public.products (${cols.join(', ')}) values
${rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(', ')})`).join(',\n')}
on conflict (slug) do nothing;
`;

await writeFile(new URL('../supabase/seed.sql', import.meta.url), sql);
console.log(`wrote supabase/seed.sql (${rows.length} products)`);
