"""Generate src/tee3d/engine.js from forauls-tiger-tee.html.

The simulation, shaders and renderer are copied verbatim from the HTML. The
standalone page UI (panel, toast, FPS readout, file pickers, window shortcuts)
is dropped and the whole thing is wrapped in

    export async function createTeeViewer(canvas, options) -> api

so React can mount, drive and destroy it. Every patch must match exactly once,
so this fails loudly if the HTML changes shape.

Usage: python -P tools/build-engine.py   (from the project root)
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
html = (ROOT / "forauls-tiger-tee.html").read_text(encoding="utf-8")
script = re.search(r"<script>\n'use strict';\n(.*)</script>", html, re.S).group(1)


def cut(src, start, end):
    """Text from the line starting with `start` up to (not including) the line starting with `end`."""
    i = src.index(start)
    j = src.index(end, i)
    return src[i:j]


def patch(src, old, new):
    n = src.count(old)
    assert n == 1, f"expected exactly one match ({n} found) for:\n{old[:120]}"
    return src.replace(old, new)


core = cut(script, "/* =====================================================================\n   Small vector", "/* =====================================================================\n   UI\n")
pointer = cut(script, "/* ---- pointer: mouse + touch", "/* =====================================================================\n   MAIN LOOP")

# ---- core patches -----------------------------------------------------------
core = patch(core, "const canvas = document.getElementById('gpu');\n", "")
core = patch(
    core,
    "  burgundy: { name: 'Burgundy',",
    "  jet:      { name: 'Jet Black', base: [0.011, 0.011, 0.012], wash: 0.16, fuzz: [0.06, 0.06, 0.065], thread: 0.006, exposure: 1.0 },\n"
    "  burgundy: { name: 'Burgundy',",
)
core = patch(core, "  frontAspect: 0.2, backAspect: 1.36,\n", "  frontAspect: 0.2, backAspect: 1.36,\n  frontRect: null, backRect: null, autoSpin: 0, userActive: false,\n")
core = patch(
    core,
    "if (info.reason !== 'destroyed') showFallback('The GPU device was lost (' + info.message + '). Reload to try again.');",
    "if (info.reason !== 'destroyed') onDeviceLost(info);",
)
# artwork can live on another origin (Supabase storage); CORS keeps it readable
core = patch(
    core,
    "const img = new Image(); img.onload = () => res(img);",
    "const img = new Image(); img.crossOrigin = 'anonymous'; img.onload = () => res(img);",
)
# capture(): one frame without the studio backdrop or pin markers, on a transparent canvas
core = patch(
    core,
    "loadOp: 'clear', storeOp: 'discard', clearValue: [0.9, 0.9, 0.91, 1] }],",
    "loadOp: 'clear', storeOp: 'discard', clearValue: captureReq ? [0, 0, 0, 0] : [0.9, 0.9, 0.91, 1] }],",
)
core = patch(
    core,
    "  pass.setPipeline(P.bgPipe); pass.setBindGroup(0, B.bgPipe); pass.draw(3);\n",
    "  if (!captureReq) { pass.setPipeline(P.bgPipe); pass.setBindGroup(0, B.bgPipe); pass.draw(3); }\n",
)
core = patch(
    core,
    "  if (gpu.pinCount) { pass.setPipeline(P.pins);",
    "  if (gpu.pinCount && !captureReq) { pass.setPipeline(P.pins);",
)
core = patch(
    core,
    "  const dpr = Math.max(0.6, Math.min(window.devicePixelRatio || 1, CFG.maxDpr) * renderScale);",
    "  const dpr = captureReq ? captureReq.dpr : Math.max(0.6, Math.min(window.devicePixelRatio || 1, CFG.maxDpr) * renderScale);",
)
core = patch(
    core,
    "  return { front: [0.135, 0.545, fw, fh], back: [0.0, 0.675 - bh / 2, bw, bh] };",
    "  return { front: state.frontRect || [0.135, 0.545, fw, fh], back: state.backRect || [0.0, 0.675 - bh / 2, bw, bh] };",
)
core = patch(
    core,
    "  document.querySelectorAll('#modeSeg .btn').forEach((b) => b.classList.toggle('on', b.dataset.mode === mode));\n"
    "  document.getElementById('modeLbl').textContent = MODE_LABEL[mode];\n",
    "  opts.onMode?.(mode);\n",
)

# ---- pointer patches: tracked listeners, page-friendly wheel, interaction flag
pointer = pointer.replace("canvas.addEventListener(", "listen(canvas, ")
pointer = patch(
    pointer,
    "    pointers.set(e.pointerId, { x: e.clientX, y: e.clientY });\n",
    "    pointers.set(e.pointerId, { x: e.clientX, y: e.clientY });\n    state.userActive = true; opts.onInteract?.();\n",
)
pointer = patch(
    pointer,
    "    pointers.delete(e.pointerId);\n",
    "    pointers.delete(e.pointerId);\n    state.userActive = pointers.size > 0;\n",
)
pointer = patch(
    pointer,
    "    e.preventDefault();\n    const dy = e.deltaMode === 1 ? e.deltaY * 16 : e.deltaY;",
    "    if (!state.grab && !(e.ctrlKey || e.metaKey)) return;   // plain wheel scrolls the page\n"
    "    e.preventDefault();\n    const dy = e.deltaMode === 1 ? e.deltaY * 16 : e.deltaY;",
)

HEADER = """/* eslint-disable */
// GENERATED by tools/build-engine.py from forauls-tiger-tee.html — do not edit by hand.
// WebGPU cloth-simulated tee: XPBD cloth on the GPU, studio lighting, prints as textures.

/**
 * Mounts the 3D tee on `canvas`.
 * options: { front, back: { src, rect? }, colour, mode, yaw, autoSpin, framing: { dy, dist }, lite,
 *            onYaw(rad), onMode(mode), onToast(msg), onInteract(), onError(err) }
 * `lite` starts (and stays) on the cheaper end of the quality ladder — used when
 * rebuilding after the GPU was reset.
 * Resolves to an API object; rejects if WebGPU is unavailable or the GPU is lost
 * during start-up. onError fires if the device is lost afterwards (driver reset,
 * TDR, sleep/wake); the instance is dead then and should be destroyed and rebuilt.
 */
export async function createTeeViewer(canvas, options = {}) {
const opts = options;
const cleanups = [];
const listen = (t, type, fn, o) => { t.addEventListener(type, fn, o); cleanups.push(() => t.removeEventListener(type, fn, o)); };
function toast(msg) { opts.onToast?.(msg); }
function updateFlipLabel() {}

"""

FOOTER = r"""
/* =====================================================================
   MAIN LOOP (adapted: start/stop, auto-spin, yaw reporting)
   ===================================================================== */
let lastT = performance.now(), acc = 0, fpsAvg = 60, scaleT = performance.now() + 2500;
const baseQuality = opts.lite ? QUALITY.length - 2 : IS_MOBILE ? 1 : 0;
let raf = 0, running = false, destroyed = false, booted = false, lostInfo = null, lastYaw = NaN;

/** A lost device can't be revived: stop submitting work and let the host rebuild us. */
function onDeviceLost(info) {
  lostInfo = info; stop();
  if (captureReq) { captureReq.reject(new Error('The GPU device was lost.')); captureReq = null; }
  if (booted && !destroyed) opts.onError?.(new Error('The GPU device was lost (' + info.message + ').'));
}

/* ---- capture: a transparent, high-resolution still of the tee (product images) ---- */
let captureReq = null, restoreOpaque = false;
const CAPTURE_VIEW = { pitch: 0.06, dist: 2.45, target: [0, 0.62, 0] };
/**
 * Renders the tee from `yaw` (0 = front, π = back) on a transparent background
 * at `dpr` × the canvas's CSS size and resolves to a 2D canvas copy of it.
 */
function capture({ yaw = 0, dpr = 2.5 } = {}) {
  if (destroyed || lostInfo) return Promise.reject(new Error('The 3D view is not running.'));
  if (captureReq) return Promise.reject(new Error('A capture is already in progress.'));
  const saved = { ...camera.goal };
  Object.assign(camera.goal, CAPTURE_VIEW, { yaw });
  Object.assign(camera, CAPTURE_VIEW, { yaw, target: [...CAPTURE_VIEW.target] });
  return new Promise((resolve, reject) => {
    const done = (fn) => (v) => {
      clearTimeout(timer);
      if (captureReq === req) captureReq = null;
      restoreOpaque = true;
      Object.assign(camera.goal, saved);
      fn(v);
    };
    const req = { frames: 2, dpr, armed: false, resolve: done(resolve), reject: done(reject) };
    const timer = setTimeout(() => req.reject(new Error('Capturing the 3D view timed out.')), 5000);
    captureReq = req;
    start();
  });
}
function captureFrame() {
  const req = captureReq;
  if (--req.frames > 0) return;
  try {
    const out = document.createElement('canvas');
    out.width = canvas.width; out.height = canvas.height;
    out.getContext('2d').drawImage(canvas, 0, 0);   // same task as the submit: reads this frame
    req.resolve(out);
  } catch (e) { req.reject(e); }
}

function frame(now) {
  if (destroyed || !running) return;
  const dt = Math.min(0.1, (now - lastT) / 1000); lastT = now;
  fpsAvg += ((1 / Math.max(dt, 1e-3)) - fpsAvg) * 0.08;
  if (!document.hidden && now - scaleT > 1500) {
    if (fpsAvg < 50 && qualityLevel < QUALITY.length - 1) { applyQuality(qualityLevel + 1); scaleT = now; }
    else if (fpsAvg > 59 && qualityLevel > baseQuality && now - scaleT > 4000) { applyQuality(qualityLevel - 1); scaleT = now; }
  }
  if (state.autoSpin && !state.userActive && !state.grab && !captureReq) camera.goal.yaw += state.autoSpin * dt;
  if (captureReq && !captureReq.armed) {
    context.configure({ device, format: canvasFormat, alphaMode: 'premultiplied' });
    captureReq.armed = true; scaleT = now;
  } else if (restoreOpaque && !captureReq) {
    context.configure({ device, format: canvasFormat, alphaMode: 'opaque' });
    restoreOpaque = false;
  }

  resizeTargets();
  updateCamera(dt);
  if (!(Math.abs(camera.yaw - lastYaw) < 1e-4)) { lastYaw = camera.yaw; opts.onYaw?.(camera.yaw); }
  let steps = 0;
  if (!state.paused) {
    acc += dt;
    const maxSteps = fpsAvg > 50 ? 2 : 1;
    while (acc >= 1 / 60 && steps < maxSteps) { acc -= 1 / 60; steps++; }
    if (acc > 1 / 30) acc = 0;
    state.shakeAmp *= Math.exp(-dt * 2.2);
    state.shakePhase += dt * 24;
    if (state.manqGrow < 1) state.manqGrow = Math.min(1, state.manqGrow + dt / 1.2);
  }
  lastView = viewInfo();

  const enc = device.createCommandEncoder();
  if (steps > 0 || gpu.needNormals) {
    state.time += steps / 60;
    writeSimUniforms();
    const pass = enc.beginComputePass();
    for (let i = 0; i < steps; i++) encodeSimStep(pass);
    encodeNormals(pass);
    pass.end();
    gpu.needNormals = false;
  }
  writeCamUniforms(lastView);
  encodeDepth(enc, gpu.shadowTex, gpu.bg.key);
  encodeDepth(enc, gpu.aoTex, gpu.bg.ao);
  encodeMain(enc);
  const rb = encodeReadback(enc);
  device.queue.submit([enc.finish()]);
  if (rb) finishReadback();
  if (captureReq) captureFrame();
  raf = requestAnimationFrame(frame);
}
function start() {
  if (running || destroyed) return;
  running = true; lastT = performance.now();
  raf = requestAnimationFrame(frame);
}
function stop() { running = false; cancelAnimationFrame(raf); }

/** Optional framing offset so the tee sits clear of overlaid UI: { dy (m), dist (scale) }. */
function applyFraming() {
  const f = opts.framing; if (!f) return;
  const t = camera.goal.target;
  camera.goal.target = [t[0], t[1] + (f.dy || 0), t[2]];
  camera.goal.dist *= f.dist || 1;
}

/** Loads front/back artwork; a rect places it on the pattern (metres: cx, cy, w, h). No print = plain fabric. */
async function applyPrint(which, p) {
  if (p?.src) await setArtwork(which, p.src);
  else clearArtwork(which);
  state[which === 'front' ? 'frontRect' : 'backRect'] = p?.rect ?? null;
}
function clearArtwork(which) {
  const blank = document.createElement('canvas'); blank.width = blank.height = 4;   // fully transparent
  const key = which === 'front' ? 'frontTex' : 'backTex';
  if (gpu[key]) { const old = gpu[key]; setTimeout(() => old.destroy(), 500); }
  gpu[key] = makeTexture(blank).tex;
  if (gpu.pipes?.shirt) buildShirtBindGroup();
}

/* =====================================================================
   BOOT
   ===================================================================== */
await initGPU();
if (opts.lite) CFG.shadowSize = 1024;
device.pushErrorScope('validation');
G = buildGarment();
createSimBuffers();
createSimPipelines();
buildHanger();
await Promise.all([applyPrint('front', opts.front), applyPrint('back', opts.back)]);
createRenderPipelines();
const bootErr = await device.popErrorScope();
if (bootErr || lostInfo) {
  device.destroy();
  throw new Error(bootErr ? bootErr.message : 'The GPU device was lost during start-up (' + lostInfo.message + ').');
}
applyQuality(baseQuality);
wirePointer();
if (opts.colour && COLOURWAYS[opts.colour]) state.colour = opts.colour;
state.autoSpin = opts.autoSpin || 0;
setMode(opts.mode || 'mannequin');
applyFraming();
camera.yaw = camera.goal.yaw = opts.yaw || 0;
lastView = viewInfo();
booted = true;
start();

return {
  /** Swap artwork: { front: { src, rect }, back: { src, rect } } */
  setPrints: (p) => Promise.all([applyPrint('front', p.front), applyPrint('back', p.back)]),
  /** Move/resize one print without reloading it: rect = [cx, cy, w, h] in pattern metres (null = default). */
  setPrintRect: (which, rect) => { state[which === 'front' ? 'frontRect' : 'backRect'] = rect ?? null; },
  /** Transparent still of the tee: { yaw, dpr } → Promise<HTMLCanvasElement>. */
  capture,
  setColour: (id) => { if (COLOURWAYS[id]) state.colour = id; },
  setMode: (m) => { setMode(m, true); applyFraming(); },
  reset: () => { setMode(state.mode); applyFraming(); },
  setWind: (on) => { state.wind = !!on; },
  shake: () => triggerShake([0, 0, 0], 1),
  setAutoSpin: (radPerSec) => { state.autoSpin = radPerSec || 0; },
  /** Orbit the camera to `rad` (smoothed); immediate skips the easing. */
  setYaw: (rad, immediate = false) => { camera.goal.yaw = rad; if (immediate) camera.yaw = rad; },
  getYaw: () => camera.goal.yaw,
  zoom: (factor) => { camera.goal.dist = clamp(camera.goal.dist * factor, 0.6, 6); },
  setActive: (on) => (on ? start() : stop()),
  destroy: () => {
    destroyed = true; stop();
    captureReq?.reject(new Error('The 3D view was closed.'));
    cleanups.forEach((f) => f());
    try { device.destroy(); } catch (e) { /* already gone */ }
  },
};
}
"""

out = HEADER + core + pointer + FOOTER
for banned in ("$(", "showFallback(", "document.getElementById"):
    assert banned not in out, f"leftover page-UI reference: {banned}"
dest = ROOT / "src" / "tee3d" / "engine.js"
dest.parent.mkdir(parents=True, exist_ok=True)
dest.write_text(out, encoding="utf-8")
print(f"wrote {dest.relative_to(ROOT)} ({len(out) // 1024} KB, {out.count(chr(10))} lines)")
